backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/web/controllers/CaseApiController.java, backend/case/src/main/java/org/pucar/dristi/web/models/CaseCodeCriteria.java, backend/case/src/main/java/org/pucar/dristi/web/models/CaseCodeRequest.java, backend/case/src/main/java/org/pucar/dristi/web/models/CaseCodeResponse.java, backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java
=> verify access code

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> join case replace task update after order generate

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
=> [hotfix-3129] Updated next hearing time from mdms

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
=> [hotfix-3129] Removed filtering in BulkReschedule

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ConfirmEvidenceAction.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
=> [hot-fix] #3547 Evidence Exhibit Number Missing & Removal of Unmarking - fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
=> [hotfix-3129] Need to have all hearings in just 1 slot and freeze time shown to advocates for case hearing to 11am

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
https://github.com/pucardotorg/dristi/issues/3423
disabled unjoined case to advocate who rasise the request and hide reason document when it not present
=> Join Case 2.0 - Disable case when advocate replac

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Css version upgrade to qa

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
=> [hotfix-3129]  Need to have all hearings in just 1 slot and freeze time shown to advocates for case hearing to 11am

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
=> [hot-fix] #3547 fixed exhibit numbering

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> removed duplicate code that was added as part of merging

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
https://github.com/pucardotorg/dristi/issues/3367
=> filterCriteria bug fix in bulk sign

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Join case enhance and bug

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
=> Profile edit join case changes

backend/analytics/src/test/java/org/pucar/dristi/util/IndexerUtilsTest.java
=> test case commented

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> add null check for name

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> condition for pip

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> update litigant for all advocates

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Added new message for advocate replacement rejected, and added litigants list in workflow for pending task transfer
=> Rejected message for advocate replacement

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> minor fixes for bulk signing

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> dev testing fixes for pip

backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/util/PendingTaskUtil.java, backend/scheduler-svc/src/main/java/digit/web/models/PendingTask.java
=> added screentype in pending task

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> adding hearingNumber on updateOrder in order page

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> date format fix in bulk sign order page

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
=> profile editing changes

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java, backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/util/EvidenceUtil.java, backend/case/src/main/java/org/pucar/dristi/validators/EvidenceValidator.java, backend/case/src/main/java/org/pucar/dristi/web/models/Artifact.java, backend/case/src/main/java/org/pucar/dristi/web/models/Comment.java, backend/case/src/main/java/org/pucar/dristi/web/models/EvidenceRequest.java, backend/case/src/main/java/org/pucar/dristi/web/models/EvidenceSearchCriteria.java, backend/case/src/main/java/org/pucar/dristi/web/models/EvidenceSearchRequest.java, backend/case/src/main/java/org/pucar/dristi/web/models/EvidenceSearchResponse.java, backend/case/src/main/resources/application.properties, backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java, backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java
=> evidence creation changes

backend/order-management/src/main/java/pucar/service/BSSService.java, backend/order-management/src/main/java/pucar/service/CompositeOrderService.java, backend/order-management/src/main/java/pucar/strategy/AdmitCase.java, backend/order-management/src/main/java/pucar/strategy/AdvocateReplacementApproval.java, backend/order-management/src/main/java/pucar/strategy/ApprovalRejectionLitigantDetailsChange.java, backend/order-management/src/main/java/pucar/strategy/AssigningDateRescheduledHearing.java, backend/order-management/src/main/java/pucar/strategy/CheckoutAcceptance.java, backend/order-management/src/main/java/pucar/strategy/DefaultOrderUpdate.java, backend/order-management/src/main/java/pucar/strategy/DismissCase.java, backend/order-management/src/main/java/pucar/strategy/ExtensionOfDocumentSubmissionDate.java, backend/order-management/src/main/java/pucar/strategy/InitiatingReschedulingOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/MandatorySumissionResponses.java, backend/order-management/src/main/java/pucar/strategy/Notice.java, backend/order-management/src/main/java/pucar/strategy/RescheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/ScheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/SchedulingNextHearing.java, backend/order-management/src/main/java/pucar/strategy/SetBailTerms.java, backend/order-management/src/main/java/pucar/strategy/Summons.java, backend/order-management/src/main/java/pucar/strategy/Warrant.java, backend/order-management/src/main/java/pucar/util/PendingTaskUtil.java
=> Added Logging in service

backend/order-management/src/main/java/pucar/service/BSSService.java, backend/order-management/src/test/java/pucar/service/BSSServiceTest.java
=> fixed test case

backend/order-management/src/main/java/pucar/service/CompositeOrderService.java
=> fixed composite order bug

backend/analytics/src/main/java/org/pucar/dristi/kafka/consumer/PendingTaskUpdateConsumer.java, backend/analytics/src/main/java/org/pucar/dristi/service/PendingTaskService.java, backend/analytics/src/main/resources/application.properties
=> transfer pending task

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BulkCheckbox.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
=> Feature 3367 selected

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BulkCheckbox.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
* selected item fix in bulk sign
* added null check
#3367
=> selected fix in bulk sign page (#2469)

backend/order-management/src/main/java/pucar/service/BSSService.java, backend/order-management/src/main/java/pucar/service/CompositeOrderService.java, backend/order-management/src/main/java/pucar/strategy/AdmitCase.java, backend/order-management/src/main/java/pucar/strategy/AdvocateReplacementApproval.java, backend/order-management/src/main/java/pucar/strategy/ApprovalRejectionLitigantDetailsChange.java, backend/order-management/src/main/java/pucar/strategy/AssigningDateRescheduledHearing.java, backend/order-management/src/main/java/pucar/strategy/CheckoutAcceptance.java, backend/order-management/src/main/java/pucar/strategy/DefaultOrderUpdate.java, backend/order-management/src/main/java/pucar/strategy/DismissCase.java, backend/order-management/src/main/java/pucar/strategy/ExtensionOfDocumentSubmissionDate.java, backend/order-management/src/main/java/pucar/strategy/InitiatingReschedulingOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/MandatorySumissionResponses.java, backend/order-management/src/main/java/pucar/strategy/Notice.java, backend/order-management/src/main/java/pucar/strategy/RescheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/ScheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/SchedulingNextHearing.java, backend/order-management/src/main/java/pucar/strategy/SetBailTerms.java, backend/order-management/src/main/java/pucar/strategy/Summons.java, backend/order-management/src/main/java/pucar/strategy/Warrant.java, backend/order-management/src/main/java/pucar/util/PendingTaskUtil.java, backend/order-management/src/test/java/pucar/service/BSSServiceTest.java
=> checkout develop

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
Disable himself replacing advocate
=> Disable himself replacing advocate

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> Feature 3423 hearings uat changes

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> Feature 3423 hearing changes qa

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
=> Feature 3423 evidence main

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> dev testing fixes for hearing

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
=> page break fix in hearing, hide button for edit ADiary

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> enrich representing name

backend/order-management/src/main/java/pucar/config/Configuration.java, backend/order-management/src/main/java/pucar/service/BSSService.java, backend/order-management/src/main/java/pucar/service/CompositeOrderService.java, backend/order-management/src/main/java/pucar/strategy/AdmitCase.java, backend/order-management/src/main/java/pucar/strategy/AdvocateReplacementApproval.java, backend/order-management/src/main/java/pucar/strategy/ApprovalRejectionLitigantDetailsChange.java, backend/order-management/src/main/java/pucar/strategy/AssigningDateRescheduledHearing.java, backend/order-management/src/main/java/pucar/strategy/CheckoutAcceptance.java, backend/order-management/src/main/java/pucar/strategy/DefaultOrderUpdate.java, backend/order-management/src/main/java/pucar/strategy/DismissCase.java, backend/order-management/src/main/java/pucar/strategy/ExtensionOfDocumentSubmissionDate.java, backend/order-management/src/main/java/pucar/strategy/InitiatingReschedulingOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/MandatorySumissionResponses.java, backend/order-management/src/main/java/pucar/strategy/Notice.java, backend/order-management/src/main/java/pucar/strategy/RescheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/ScheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/SchedulingNextHearing.java, backend/order-management/src/main/java/pucar/strategy/SetBailTerms.java, backend/order-management/src/main/java/pucar/strategy/Summons.java, backend/order-management/src/main/java/pucar/strategy/Warrant.java, backend/order-management/src/main/java/pucar/util/PendingTaskUtil.java, backend/order-management/src/main/java/pucar/web/models/pendingtask/Inbox.java, backend/order-management/src/main/java/pucar/web/models/pendingtask/InboxRequest.java, backend/order-management/src/main/java/pucar/web/models/pendingtask/InboxResponse.java, backend/order-management/src/main/java/pucar/web/models/pendingtask/InboxSearchCriteria.java, backend/order-management/src/main/java/pucar/web/models/pendingtask/ProcessInstanceSearchCriteria.java, backend/order-management/src/main/resources/application.properties
=> Order management develop to main

backend/order-management/src/main/java/pucar/service/CompositeOrderService.java
=> composite order bug fix

backend/order-management/src/main/java/pucar/service/BSSService.java
=> uncommented code in bss service

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/validators/EvidenceValidator.java
=> reason document evidence submission

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
warrant payment modal -> issuedTo:  is showing object object instead of name - handled object as well as string
=> warrant payment modal -> issuedTo: is showing object object instead of name

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/validators/EvidenceValidator.java
=> litigant duplicate and updating courtcase for redis

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersNotificationService.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
=> loading fix, localization change and preselect status filter

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> [hotfix-3278] Judge page issues with longer case names

backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
=> changed to double

common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/config/ApplicationConfiguration.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/config/EmailProperties.java, common/egov-notification-mail/src/main/resources/application.properties
=> Radheshjoshi1 patch 2

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/evidence/src/main/resources/application.properties
=> Sms templates join case

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/validators/EvidenceValidator.java
=> Merge main to develop 2apr fe

common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/config/EmailProperties.java
=> fixed the email properties

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentEsign.js
=> [hot-fix] #3497 fixed post esign redirect

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Fix for order Shifted to one

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Fix for correct redirection of orders

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Merge main to develop april 3 fe

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Hotfix 3476 3644 uat redirection order type fix

support/3497-mdms-role.json
=> Support file added #3497

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
=> [bug-fix] #3497 alignment fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Removed duplicate submission option and fixed submitted by name issue for clerk and judge.
https://github.com/pucardotorg/dristi/issues/3497#issuecomment-2778097892
=> [hot-fix] #3497 removed duplicate submission option and fixed submitted by name issue for clerk and judge

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/PaymentModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> Application fee change from 2 to 20

backend/treasury-backend/src/main/java/org/egov/eTreasury/model/BreakDown.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/service/PaymentService.java
=> add code attribute to breakdown

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java, backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java, backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
=> Bug 3492 main others application type cmp number

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> Sending bill amount from Fetch Bill

backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java, support/3647-mdms-data.json
=> Bug 3668 updated mdms data for nyaymitra payment

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
=> Join case Payment fix

backend/transformer/src/main/java/org/egov/transformer/service/HearingService.java
=> Bug 3586 main open hearing case number enrichment

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> [bug-fix] #3411 - Voluntary Submission is displaying as status as completed Fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
=> Enhance More precise Condition

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> [bug-fix] Remove blocker #3411

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> [hot-fix] #3680 process banner for composite order fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> [bug-fix] #3411 minor bug fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> [bug-fix] #3691 Fixed - hearing date displaying if hearing is not active

backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java, backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/CaseFeeCalculationServiceTest.java
=> Removed Application Fees

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> [bug-fix] Minor fix #3411

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
=> placholder name fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> [hot-fix] #3680 Fixed process banner for composite order

backend/dristi-case-pdf/util/formatUtil.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
=> removing extra spaces in acronym

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> [bug-fix] #3661 Warrant payment issue fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
=> updated process env

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
=> updating esign panel condition

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
=> duplicate pending task issue fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js, support/3358-mdms.json
=> added police station in cheque details

support/3358-mdms.json
=> added Style in Config

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> poa join case revert

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> Update navbar and admitted case header zIndex and positioning styles

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/PaymentModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js, support/1.6.0-3711-mdms-schema.json, support/1.6.0.3711-mdms-data.json
=> Move the application Amount to mdms

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
=> Remove ConfirmCorrectionModal

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> Update default isVakalatnamaNew values from "NO" to "YES"

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
=> [Enhancement-3486] FSO: Give remarks option to the FSO

backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/enrichment/IcopsEnrichment.java, backend/scheduler-svc/src/main/java/digit/web/models/hearing/Hearing.java, backend/summons-svc/src/main/java/digit/web/models/DeliveryChannel.java, backend/task/src/main/java/org/pucar/dristi/service/TaskService.java, backend/task/src/main/java/org/pucar/dristi/util/SummonUtil.java, backend/task/src/main/java/org/pucar/dristi/web/models/SummonsDelivery.java, backend/task/src/test/java/org/pucar/dristi/util/SummonUtilTest.java
=> update task object for acknowledgement id

backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
=> update tsb data

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/GetPoliceStationModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Issue: https://github.com/pucardotorg/dristi/issues/3649 --> more changes 
Changes after the icops api integration is successful in backend
=> Changes after the icops api integration is successful in backend

backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
=> update pdf creation for warrant pdf

backend/summons-svc/src/main/java/digit/channel/ChannelFactory.java, backend/summons-svc/src/main/java/digit/channel/RpadChannel.java, backend/treasury-backend/src/main/resources/application.properties
=> add rpad channel for summons

support/v1.6.0/release-1.6.0-3647-mdms.json5
=> 3647 support folder changes

backend/summons-svc/src/main/java/digit/service/SummonsService.java
=> change executed to delivered

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js, support/3650-mdms-data-review-case-file.json, support/3650-mdms-data.json
- Add POA age field in complaint details form
- Add age validation with max length 3 and number pattern
- Fix POA holder name display by using textTitle type -UI styling improvements
- #3744
- #3745
=> POA FSO fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Issue: https://github.com/pucardotorg/dristi/issues/3752, https://github.com/pucardotorg/dristi/issues/3753,
https://github.com/pucardotorg/dristi/issues/3754, https://github.com/pucardotorg/dristi/issues/3756
=> [Issue 3752, 3753, 3754, 3756]made changes for the specified issues- cherry-pick in develop

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Issue: https://github.com/pucardotorg/dristi/issues/3752, https://github.com/pucardotorg/dristi/issues/3753,
https://github.com/pucardotorg/dristi/issues/3754, https://github.com/pucardotorg/dristi/issues/3756
=> [Issue 3752, 3753, 3754, 3756]made changes for the specified issues

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> For Schedule Next hearing Botd change

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> Updated Application Fee Amount

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> setting purposeOfHearing from formData as well in botd of hearing date

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
=> updated css

support/v1.6.0/3625-mdms-data.json
=> add mapping for join case

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js, support/3358-mdms.json
=> change the policeStation key for chequeDetails

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Release sprint19 to main

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
remove non-digits, leading zeros, and limit to 3 chars #3699
=> Sanitize noOfAdvocates input

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
=> update start date

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
=> [BUG 3761]: [UAT] [The issued to is displayed as Object Object for the warrant] 

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
=> Add bill details to handleButtonClick and update bill search params

support/v1.6.0/3623-mdms-data.json, support/v1.6.0/3625-mdms-data.json
=> data add for warrant post

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Issue: #3763
added sbi payments option for warrant epost
=> added sbi payments option for warrant epost

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Issue: #3763
closing pending tasks for warrant payments
=> [bug 3763- updated]: closing pending tasks for warrant payments

backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/config/ServiceConstants.java, backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java, backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/EFilingParam.java, backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/helper/EFilingParamTestBuilder.java, backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/CaseFeeCalculationServiceTest.java, support/v1.6.0/release-1.6.0-3712-mdms-data.json, support/v1.6.0/release-1.6.0-3712-mdms-schema.json
=> Enhancement 3712 rename petiotion fee main

utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
=> key name for newHearingDate fix in reschedule hearing date order pdf

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> new botd for Rescheduling of hearing date

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
Issue: #3750
Added POA related data in payload, so that judge can see whole data when comparing newer and older data.
=> [#3750: profile editing Issue after Introduction of POA]

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
=> Removed "Search Case Id" field from Total Hearings tab

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
=> Fix for  judgement Date

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
=> fixed esign pending tasks for poa

support/18.4/3500-mdms-data.json
=> Bail Application: Added 'OTHERS' to SubmissionDocumentType

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
=> Complainant's Id issue fixed 

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
=> remove debugger

backend/analytics/src/main/java/org/pucar/dristi/web/models/PendingTask.java
=> added the field level validation back for pending task

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Change deliveryChannel appearance for warrant Order

frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/pages/employee/SummonsNWarrantsModal.scss, frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/prehearing.scss, frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/homehearing.scss
=> Fixed alignment of sort filters

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> [enhancement-3653] COURTSTAFF: Enhancement on Review Notice/Summons View

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Fix for auto populate police data

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
=> Enhancement 3653

backend/order-management/src/main/java/pucar/service/CompositeOrderService.java
=> for multiple composite item null check

backend/casemanagement/src/main/java/org/pucar/dristi/Main.java, backend/casemanagement/src/main/java/org/pucar/dristi/config/DataSourceConfig.java, backend/casemanagement/src/main/java/org/pucar/dristi/repository/CaseBundleRepository.java, backend/casemanagement/src/main/java/org/pucar/dristi/repository/PdfResponseRepository.java, backend/casemanagement/src/main/resources/application.properties
=> added database source config for read and

support/v1.6.2/3742-mdms-data.json
=> Added wildcard operator to caseTitle for inbox search

common/inbox/src/main/java/org/egov/inbox/repository/builder/V2/InboxQueryBuilder.java
=> Bug 3742 inbox search wildcard case insensitive main

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
=> Issued To fix in payment modal for composite order

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
=> Removal of policeStation Condition on warrant

backend/order-management/src/main/java/pucar/service/CompositeOrderService.java
=> fix hearing number enrichment in composite order

support/v1.6.2/3815-mdms-data.json5
=> 3815 support folder changes

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EndHearing.js
=> Case is having two Hearings fixed 

backend/order-management/src/main/java/pucar/util/HearingUtil.java
=> change if condition

backend/order-management/src/main/java/pucar/service/OrderService.java
=> update order case entry check

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useFetchBill.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
=> switching billSearch to fetchBill for task related payments

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EndHearing.js
=> Case is having two Hearings fixed

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> Homescreen Change CaseId -> Case Number

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
=> [hotfix-3471] Changed BOTD for bulk rescheduling

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
=> Cases with hearings ended should also be navigatable from the calendar view

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
=> aded back search case Id field 

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> Enhancement on Review Notice/Summons View

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ChangePassword/changePassword.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ForgotPassword/forgotPassword.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/LanguageSelection/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
=> Removed "Powered by Digit" from footer

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
=> Feature 3779 3772 to main

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
added localization in document type
#3430
=> added localization in document type (#2885)

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Upgrade css version

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
updated filter condition 
#3856
=> updated filter condition

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
=> Added prev hearing and show transcript for dismissed cases 

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
=> reIssue pending task fix

backend/order/src/test/java/org/pucar/dristi/service/OrderRegistrationServiceTest.java
=> fixed order test

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/Module.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
=> Made Combined View for Notice, Summons and warrant process

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> Reduce cache time

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js, support/19.2/3829-mdms-schema.json
=> Efiling screen proof of service of legal demand notice fields changed

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
=> Remove fields showing "OutlinedInfoIcon" once a case is sent back

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Hotfix 3452 new figma

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
=> NonWorking days marked as red in Calendar 

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Added bydefault for via police and fix for trim text

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> prevent access code from double encryption

backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
=> Bug 68 timezone fix recent cause list main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
=> updated boolen condition

backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
=> Bug 3653 added fee paid date deliver channels main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/orderWorkflow.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, support/v1.6.4/3831-mdms-data.json
=> Hitfix 3831 uat

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Added Process Fee Paid on Date in Review Summon, Warrant & Notices.

backend/scheduler-svc/src/main/java/digit/service/IndividualService.java
=> Fixed deleted Individual Search

backend/order-management/src/main/java/pucar/web/models/Order.java
=> update import for order document

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetTaskList.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/index.js
=> Feature 2829 main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Feature 3771 main

backend/order-management/src/main/java/pucar/strategy/DefaultOrderUpdate.java, backend/order-management/src/main/java/pucar/strategy/Notice.java, backend/order-management/src/main/java/pucar/strategy/ScheduleOfHearingDate.java, backend/order-management/src/main/java/pucar/strategy/Summons.java, backend/order-management/src/main/java/pucar/strategy/Warrant.java
=> updated syntax

support/v1.6.4/3771-mdms-data.json5
=> added support folder for 3771

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
=> Feature 3872 reIssue pending task fix, edit case pendingTask fix while uploadDoc

backend/analytics/src/main/java/org/pucar/dristi/web/models/PendingTask.java
=> added not null in case id and title

backend/Notification/src/main/java/notification/util/FileStoreUtil.java, backend/ab-diary/src/main/java/digit/util/FileStoreUtil.java, backend/application/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/case/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/hearing/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/order/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/task/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
=> change request body

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSetBailTerms.java
=> added parameter in individual call

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EmployeeProfileEdit/EmployeeProfileEdit.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageUpload/UploadDrawer.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
=> Add employee profile edit functionality with password change (#2967)

backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderAdmitCase.java
=> updated hearing to completed and removed schedule hearing pending task

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearings.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
=> updated misssed code from dev to main

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> CSS version ugrade

utilities/dristi-pdf/src/utils/commonUtils.js
=> hrms filter in pdf bug fix

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js, support/v1.6.4/2287-mdms-data.json5
updated  to delete unsigned filestore
=> updated  to delete unsigned filestore

utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
=> fixed signature placeholder for judge

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderAdmitCase.java
#3562
#3910
updating hearing with close state throwing invalid action exception from workflow
=> reverted 3562 issue for admit case order

backend/Notification/src/main/java/notification/repository/rowmapper/NotificationRowMapper.java
* additional details to json
* additional details to json
=> Notificaiton additional details fix (#3028)

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> changing redirection of bulkSign popup close

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
=> [#3920]: handled undefined sub address values fields

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> Removed freezing of upper half of View Case page 

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
=> updated css (#3048)

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderAdmitCase.java
=> removed hearing abated logic from admit case

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DocumentDetailCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
=> Added preview of documents during registration approval on Nyaymitra

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
=> Added preview of uploaded document 

backend/summons-svc/src/main/java/digit/config/ServiceConstants.java, backend/summons-svc/src/main/java/digit/service/SummonsService.java
=> add policestation report to task documents

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
=> User Registration with Seperate Address

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
=> Enhacment 3932 sepearte address dev

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Issue: #3683
As what has been finalised in the above mentioned ticket we have implemented the following:
Depending upon the case status, now we show order for dismiss/admit case in the dropdown list in generate orders screen.
=> [#3683]: added order for admit/dismiss case in orders dropdown list in generate orders screen.

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
* updated url in notice demand error modal
* removed debugger
updated url in notice demand error modal
#3943
=> updated url in notice demand error modal (#2959)

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Upgrade css version (#3102)

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
* feat: add vakalatnama document viewer to advocate replacement component
* fix: remove hardcoded name fallback and conditionally render vakalatnama section based on document availability
#3939
=> feat: add vakalatnama document viewer to advocate replacement component

backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
=> set active field for document

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/Module.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BreadCrumbNew.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/BreadCrumbNew.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
=> Add breadcrumbs to Order & View Case Page & Fix conflicts

backend/treasury-backend/src/main/java/org/egov/eTreasury/config/ServiceConstants.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/model/TreasuryPaymentData.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/repository/TreasuryMappingRowMapper.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/service/PaymentService.java, backend/treasury-backend/src/main/java/org/egov/eTreasury/util/DemandUtil.java, backend/treasury-backend/src/test/java/org/egov/eTreasury/service/PaymentServiceTest.java
=> payment receipt migration to main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
=> showing payment receipt in fso review page (#3091)

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java, backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java, backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java, backend/case/src/main/java/org/pucar/dristi/util/EtreasuryUtil.java, backend/case/src/main/resources/application.properties, backend/case/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java
=> enrich case for payment receipt

backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java, backend/case/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java
=> build failure fix

backend/summons-svc/src/main/java/digit/web/models/DeliveryChannel.java
=> enrich delivery channel for fields

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
=> Added Reson for Filing Info in evidence modal

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
=> updated file name

frontend/micro-ui/web/micro-ui-internals/packages/css/src/submissions/submissionApplication.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
=> Minor css fixes

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js, support/21/3930-mdms-complainant-config.json, support/21/3930-mdms-reviewCaseFile-config.json
=> Have permanent as well as residential address of complainant during filing

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
=> added access of adiary to clerk

backend/ab-diary/src/main/java/digit/config/Configuration.java, backend/ab-diary/src/main/java/digit/enrichment/ADiaryEnrichment.java, backend/ab-diary/src/main/java/digit/service/DiaryService.java, backend/ab-diary/src/main/java/digit/util/FileStoreUtil.java, backend/ab-diary/src/main/java/digit/web/models/CaseDiaryDocument.java, backend/ab-diary/src/main/resources/application.properties
=> Feature 1924 abdiary main

backend/casemanagement/src/main/java/org/pucar/dristi/config/Configuration.java, backend/casemanagement/src/main/java/org/pucar/dristi/service/CaseBundleIndexBuilderService.java, backend/casemanagement/src/main/java/org/pucar/dristi/service/CaseBundleService.java, backend/casemanagement/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/casemanagement/src/main/resources/application.properties
=> Feature 1924 case bundle

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java, backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/case/src/main/resources/application.properties, backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java
=> Feature 1924 case main

backend/Notification/src/main/java/notification/config/Configuration.java, backend/Notification/src/main/java/notification/enrichment/NotificationEnrichment.java, backend/Notification/src/main/java/notification/repository/querybuilder/NotificationQueryBuilder.java, backend/Notification/src/main/java/notification/repository/rowmapper/NotificationRowMapper.java, backend/Notification/src/main/java/notification/service/NotificationService.java, backend/Notification/src/main/java/notification/util/FileStoreUtil.java, backend/Notification/src/main/java/notification/web/models/Document.java, backend/Notification/src/main/java/notification/web/models/Notification.java, backend/Notification/src/main/resources/application.properties, backend/Notification/src/main/resources/db/migration/main/V20250507122500__notification__ddl.sql, backend/Notification/src/test/java/notification/enrichment/NotificationEnrichmentTest.java, backend/Notification/src/test/java/notification/service/NotificationServiceTest.java
=> Feature 1924 notification main

backend/hearing/src/main/java/org/pucar/dristi/config/Configuration.java, backend/hearing/src/main/java/org/pucar/dristi/repository/HearingRepository.java, backend/hearing/src/main/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilder.java, backend/hearing/src/main/java/org/pucar/dristi/repository/rowmapper/HearingDocumentRowMapper.java, backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java, backend/hearing/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/Document.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/Hearing.java, backend/hearing/src/main/resources/application.properties, backend/hearing/src/main/resources/db/migration/main/V20250505175500__hearing__ddl.sql, backend/hearing/src/test/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichmentTest.java, backend/hearing/src/test/java/org/pucar/dristi/repository/HearingRepositoryTest.java, backend/hearing/src/test/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilderTest.java, backend/hearing/src/test/java/org/pucar/dristi/repository/rowmapper/HearingDocumentRowMapperTest.java, backend/hearing/src/test/java/org/pucar/dristi/validator/HearingRegistrationValidatorTest.java
=> Feature 1924 hearing main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
remove hardcoded court ID from case search criteria
=> remove hardcoded court ID from case search criteria

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useSearchCaseListService.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
add case list search endpoint and service with updated UI integration
=> add case list search endpoint and service with updated UI integration

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
=> change courtId from JudgeId

backend/case/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
=> update files delete

frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/BulkReschedule.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleTable.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
=> Allow Custom Dates in Bulk Rescheduling

backend/Notification/src/main/java/notification/util/FileStoreUtil.java, backend/ab-diary/src/main/java/digit/util/FileStoreUtil.java, backend/application/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/case/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/hearing/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/order/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, backend/task/src/main/java/org/pucar/dristi/util/FileStoreUtil.java
=> moving from sol dev to uat

backend/ab-diary/src/test/java/digit/repository/querybuilder/DiaryEntryQueryBuilderTest.java, backend/ab-diary/src/test/java/digit/repository/querybuilder/DiaryQueryBuilderTest.java, backend/ab-diary/src/test/java/digit/repository/rowmapper/DiaryEntryRowMapperTest.java
=> fixed test failure

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
=> fixing nyay mitra filters

backend/order-management/src/main/java/pucar/web/models/Order.java
=> enrich order for document

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/publishedNotificationModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
=> Change to courtId form JudgeId

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
auto-populate name fields when verifying phone number fix
=> auto-populate name fields when verifying phone number fix

backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java
=> added check for completed hearing

support/21/3992-mdms-generateSummons-endpoint.json5
=> added mdmsdata for generate summon url

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> Case filestore revert

backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java
=> Null check before deleting documents

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js
=> UI re-directed to Error window after clicking on Profile icon fixed

backend/analytics/src/main/java/org/pucar/dristi/Main.java, backend/analytics/src/main/java/org/pucar/dristi/config/Configuration.java, backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java, backend/analytics/src/main/resources/application.properties, backend/analytics/src/test/java/org/pucar/dristi/config/ServiceConstantsTest.java
=> MultiInstanceUtil Bean imported

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
=> Have document title appear in filing name (case view)

backend/hearing/src/main/java/org/pucar/dristi/config/Configuration.java, backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java, backend/hearing/src/main/java/org/pucar/dristi/util/SchedulerUtil.java, backend/hearing/src/main/resources/application.properties, backend/hearing/src/test/java/org/pucar/dristi/service/HearingServiceTest.java, backend/scheduler-svc/src/main/java/digit/service/HearingService.java, backend/scheduler-svc/src/main/java/digit/web/controllers/HearingApiController.java
=> Allowing custom selection date for bulk rescheduling

backend/hearing/src/main/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilder.java, backend/order-management/src/main/java/pucar/config/Configuration.java, backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/service/OrderService.java, backend/order-management/src/main/java/pucar/strategy/HearingUpdateStrategy.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateBasedOnStatus.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateWithOutWorkFlow.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateWithWorkflow.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSchedulingNextHearing.java, backend/order-management/src/main/java/pucar/util/HearingUtil.java, backend/order-management/src/main/resources/application.properties
=> added strategy pattern to update workflow accordingly

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/VerifyMultipartyLitigantconfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
add screen-specific name field population in phone verification flow
=> add screen-specific name field population in phone verification flow

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js, utilities/dristi-pdf/src/utils/orderUtils.js
=> Change of the order name for admit case to take cognizance

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js
=> add disbality for text fiedl when fso returned

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleTable.js
=> change caseName to title

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
=> updated password

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
=> fso judgeId fix

backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/DeliveryStatus.java, backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/service/IcopsService.java, backend/summons-svc/src/main/java/digit/kafka/SummonsConsumer.java, backend/summons-svc/src/main/java/digit/service/SummonsService.java, backend/summons-svc/src/main/java/digit/web/models/DeliveryStatus.java
=> added extra status update through icops

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Esign Redirection Issue

backend/hearing/src/main/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilder.java, backend/hearing/src/main/java/org/pucar/dristi/repository/rowmapper/HearingRowMapper.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/Hearing.java, backend/hearing/src/main/resources/db/migration/main/V20250527104200__hearing_summary_ddl.sql, backend/hearing/src/test/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilderTest.java, backend/hearing/src/test/java/org/pucar/dristi/repository/rowmapper/HearingRowMapperTest.java, backend/order-management/src/main/java/pucar/config/Configuration.java, backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/service/OrderService.java, backend/order-management/src/main/java/pucar/strategy/HearingUpdateStrategy.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateBasedOnStatus.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateWithOutWorkFlow.java, backend/order-management/src/main/java/pucar/strategy/hearing/HearingUpdateWithWorkflow.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSchedulingNextHearing.java, backend/order-management/src/main/java/pucar/util/HearingUtil.java, backend/order-management/src/main/java/pucar/web/models/Order.java, backend/order-management/src/main/java/pucar/web/models/hearing/Hearing.java, backend/order-management/src/main/resources/application.properties, backend/scheduler-svc/src/main/java/digit/config/Configuration.java, backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/service/HearingService.java, backend/scheduler-svc/src/main/java/digit/task/ScheduledTask.java, backend/scheduler-svc/src/main/java/digit/util/HearingUtil.java, backend/scheduler-svc/src/main/java/digit/web/models/WorkflowObject.java, backend/scheduler-svc/src/main/java/digit/web/models/hearing/Hearing.java, backend/scheduler-svc/src/main/resources/application.properties
* added hearing summary in hearing service
* updating PASSED_OVER and scheduled to abated state
* added workflow-abandon role to internal user
* added createdtime for pending tasks (#3253)
* added strategy pattern to update workflow accordingly (#3257)
* added strategy pattern to update workflow accordingly
* updating hearing based on status
* added check for create call
* hearing summary changes
* fixed failing test cases
=> Feature 3999 hearing summary (#3246)

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java, backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java, backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java, backend/hearing/src/test/java/org/pucar/dristi/service/HearingServiceTest.java, backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java, backend/order/src/test/java/org/pucar/dristi/service/OrderRegistrationServiceTest.java, backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
* filtering inactive documents
* added test cases
=> filtering inactive documents (#3305)

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> CSS upgrading version

backend/scheduler-svc/src/main/java/digit/config/Configuration.java, backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/service/CauseListEmailService.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java, backend/scheduler-svc/src/main/java/digit/web/models/email/Email.java, backend/scheduler-svc/src/main/java/digit/web/models/email/EmailRequest.java, backend/scheduler-svc/src/main/resources/application.properties, backend/scheduler-svc/src/test/java/digit/service/CauseListEmailServiceTest.java, support/21/3850-causeList-email-Template-mdms.json5
=> Enhancement 3850 email cause list qa

backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/analytics/src/main/java/org/pucar/dristi/util/BillingUtil.java
=> added filingnumber in bill index and format code

backend/scheduler-svc/src/main/java/digit/config/Configuration.java, backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/service/CauseListEmailService.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java, backend/scheduler-svc/src/main/java/digit/web/models/email/Email.java, backend/scheduler-svc/src/main/java/digit/web/models/email/EmailRequest.java, backend/scheduler-svc/src/main/resources/application.properties, backend/scheduler-svc/src/test/java/digit/service/CauseListEmailServiceTest.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/consumer/EmailNotificationListener.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/utils/Constants.java, support/21/3850-causeList-email-Template-mdms.json5
=> Enhancement 3850 email causelist main

support/21/3889-mdms-pending-task-for-correcttion-petition.json5
=> Profile Editing Mdms changes

backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java, backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java, backend/evidence/src/main/java/org/pucar/dristi/web/models/EvidenceSearchCriteria.java, backend/evidence/src/test/java/org/pucar/dristi/service/EvidenceServiceTest.java
=> enrichment of evidence search

backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java, backend/analytics/src/main/java/org/pucar/dristi/web/models/PendingTaskType.java, backend/analytics/src/main/java/org/pucar/dristi/web/models/ReferenceEntityTypeNameMapping.java, backend/analytics/src/test/java/org/pucar/dristi/web/models/PendingTaskTypeTest.java, support/21/3889-mdms-pending-task-for-correcttion-petition.json5
=> Enhancement 3889 litigant profile editing main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
=> fix for joined accused

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Css upgrade

backend/casemanagement/src/main/java/org/pucar/dristi/service/CaseBundleIndexBuilderService.java
=> commented extract and remove filestore

support/1.6.8/3850-causeList-email-Template-mdms.json5, support/1.6.8/3889-mdms-pending-task-for-correcttion-petition.json5, support/1.6.8/4044-hearing-priority-cognizance-applicationReview-mdms-data.json5, support/21/4044-hearing-priority-cognizance-applicationReview-mdms-data.json5
=> Hearing Priority added for Cognizance and Application review

backend/scheduler-svc/src/main/java/digit/config/Configuration.java, backend/scheduler-svc/src/main/java/digit/kafka/cosumer/HearingConsumer.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java, backend/scheduler-svc/src/main/java/digit/service/HearingService.java, backend/scheduler-svc/src/main/java/digit/service/hearing/HearingProcessor.java, backend/scheduler-svc/src/main/java/digit/util/HearingUtil.java, backend/scheduler-svc/src/main/java/digit/web/controllers/HearingApiController.java, backend/scheduler-svc/src/main/java/digit/web/models/hearing/RetryHearingRequest.java, backend/scheduler-svc/src/main/resources/application.properties, backend/scheduler-svc/src/test/java/digit/kafka/consumer/HearingConsumerTest.java, backend/scheduler-svc/src/test/java/digit/service/hearing/HearingProcessorTest.java, backend/scheduler-svc/src/test/java/digit/util/HearingUtilTest.java
=> Bug 4015 hearing update time retry mechanism qa

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
=> Fix for Complaint Issue  when case return from fso

backend/case/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
=> created new variable for cognizance sms

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Upgrade cs version

utilities/dristi-pdf/src/caseBundle/utils/getDynamicSectionNumber.js
=> removed unnecessary import

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/VerifyMultipartyLitigantconfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCasePayment.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawer.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Develop to main 4076 4088

backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java
=> null check before enriching

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> Feature 3990 redirection enhancement to main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js, utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js, utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js, utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js, utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js, utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js, utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js, utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js, utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
=> showed rejected and pendingDocUpload applications, fixed localization in pdf docket

backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java, backend/hearing/src/test/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichmentTest.java, backend/transformer/src/main/java/org/egov/transformer/models/Hearing.java, backend/transformer/src/main/java/org/egov/transformer/models/OpenHearing.java, backend/transformer/src/main/java/org/egov/transformer/service/HearingService.java
=> enhanced hearing measurement logic

backend/hearing/src/main/java/org/pucar/dristi/util/WorkflowUtil.java
=> updated uri for process instance

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/SideBarItem.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
not re-directing to case view screen on start hearing
=> not re-directing to case view screen on start hearing

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
=> fixed mark as evidence in case file ui

backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
=> added typist role

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/admission.scss, frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
https://github.com/pucardotorg/dristi/issues/4118
=> hearing type field should have a scrolling option for dropdown fixed

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Css update

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrawer.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
https://github.com/pucardotorg/dristi/issues/4126
=> Enhancement 4126 to dev

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
updated localiztaion in hearing view
=> updated localiztaion in hearing view

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/HearingTranscriptModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
=> [#4129]: added back hearings tab for employee

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/HearingTranscriptModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
=> [#4129 to develop]: added back hearings tab for employee

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> added loader

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> added source type for reason document

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ExtraComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BreadCrumbHearings.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
=> [#4129 update]: fixed court id for payload, breadcrumbs for hearing screen for citizen

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> prevent name update

backend/evidence/src/test/java/org/pucar/dristi/service/EvidenceStatusUpdateServiceTest.java
=> fixed failing test cases

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
https://github.com/pucardotorg/dristi/issues/4104
=> Prefiled details are appearing in Application details 

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> added status for reason document

backend/hearing/src/main/java/org/pucar/dristi/util/InboxUtil.java
=> passing data for mapping

utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js, utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js, utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js, utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js, utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js, utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js, utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js, utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js, utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js, utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js, utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js, utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
=> changes for docket naeOfFiling and counsel in case bundle pdf

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawer.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
=> fixed dropdown selection for citizen hearing page

backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java, backend/hearing/src/main/java/org/pucar/dristi/util/InboxUtil.java
=> added search api for confirming update

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
=> page redirecting after clicking e-sign button

backend/summons-svc/src/main/java/digit/channel/ICopsChannel.java, backend/summons-svc/src/main/java/digit/config/Configuration.java, backend/summons-svc/src/main/java/digit/config/ServiceConstants.java, backend/summons-svc/src/main/java/digit/service/SummonsService.java, backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java, backend/summons-svc/src/main/java/digit/web/models/WarrantDetails.java, backend/summons-svc/src/main/resources/application.properties
=> Enhance 3852 icops

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
=> [#4166]: timeline changes on overview screen

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
=> [#4166 updated css]

utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js
=> fixed sectionNumber in async for case bundle pdf

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BreadCrumb.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeHeader.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Feature 4213 dev

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> Fixed breadcrumb issues on refresh

backend/dristi-case-pdf/controller/caseController.js
=> paragragh tag is diplsying in downloaded PDF

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
=> added missing import

backend/task/src/main/java/org/pucar/dristi/enrichment/TaskRegistrationEnrichment.java
=> enrich reference id for generic task

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/package.json, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomGroupedDropdown.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> creation of Grouped Dropdown for warrant

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Added "Save and Sign later" option to typist/clerk

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
updated date validation condition
#4163
=> updated date validation condition

backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
=> update task for empty receipt

backend/treasury-backend/src/test/java/org/egov/eTreasury/service/PaymentServiceTest.java
=> fix test case for treasury

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> Correction of Serial number on Pagination

backend/analytics/src/main/java/org/pucar/dristi/service/BillingService.java, backend/analytics/src/main/java/org/pucar/dristi/util/BillingUtil.java
=> split consumer code for correct suffix

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
=> redirection from case - back to home screen fixed

support/v1.7.1/bug-4232-roles.json5
=> support file for typist/clerk role

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> CSS upgrade (#3627)

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
=> exclude roles for generic pending task

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderNotice.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSummons.java, backend/order-management/src/main/java/pucar/util/PendingTaskUtil.java, backend/task/src/main/java/org/pucar/dristi/service/TaskService.java, backend/task/src/main/resources/application.properties
=> added suggested changes (#3639)

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
=> update excluded role for generic-task

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> Set default value to 30

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
updated date field to have default value
#4250
=> updated date field to have default value

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
=> added filters in page redirection from homescreen to case

backend/hearing/src/main/java/org/pucar/dristi/util/OrderUtil.java
=> fixed issue while dev testing

backend/treasury-webpage/app.js, frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js, frontend/micro-ui/web/src/setupProxy.js
=> Bug 4258 qa

backend/hearing/src/main/java/org/pucar/dristi/util/DemandUtil.java, backend/hearing/src/main/java/org/pucar/dristi/util/TaskUtil.java, backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java, backend/scheduler-svc/src/main/java/digit/service/HearingService.java
=> roles update for cron job

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
=> added validation for amount

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
=> Address issue while registeration of user fixed

backend/openapi/src/main/java/org/pucar/dristi/service/OpenApiService.java
=> updated sorting path

backend/transformer/src/main/java/org/egov/transformer/models/CaseSearch.java, backend/transformer/src/main/java/org/egov/transformer/service/CaseService.java
=> Added and enriched caseSubStage field in CaseSearch

backend/openapi/src/main/java/org/pucar/dristi/service/OpenApiService.java, backend/openapi/src/main/java/org/pucar/dristi/web/models/FilterCriteria.java, backend/openapi/src/main/java/org/pucar/dristi/web/models/LandingPageCase.java, backend/openapi/src/test/java/org/pucar/dristi/service/OpenApiServiceTest.java, support/v.1.8.0-sprint-22/feature-4164-Case-Search-mdms.json5
=> Landing Page caseSubStage criteria added

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
=> updated max amount condition

support/22/4168-workflow.json
=> update state of payment after resubmission

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
=> Search bar issue fixed

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
=> edit additional details for workflow

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js, support/22/4163-mdms-data-casebundle.json, support/22/4163-mdms-data-pamenttype.json, support/22/4163-mdms-schema.json
added litigants id in additional details
=> added litigants id in additional details

backend/transformer/src/main/java/org/egov/transformer/service/CaseService.java
=> Fixed caseSubStage null error

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
=> add null check for representatives

support/v.1.8.0-sprint-22/feature-4164-Case-Search-mdms.json5
=> wildcard added for names criteria

backend/transformer/src/main/java/org/egov/transformer/service/CaseService.java
=> Add null check for courtId and tenantId

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
not showing additional info when comment is not there
=> not showing additional info when comment is not there

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> Changed Sr. Nos to freezed SerialNumber for the hearings on Home heaiing page

backend/transformer/src/main/java/org/egov/transformer/config/ServiceConstants.java, backend/transformer/src/main/java/org/egov/transformer/models/Pagination.java, backend/transformer/src/main/java/org/egov/transformer/service/CaseService.java
=> Update criterion for enriching nextHearingDate and hearingType in caseSearch

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
=> commented the Learn more

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
=> updated condition

backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceStatusUpdateService.java
=> enrich evidence criteria with filingnumber

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Blocked MARK AS SENT button after clicking

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/casemanagement/src/main/resources/application.properties, backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderNotice.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderScheduleOfHearingDate.java, support/22.1/4187-mdms-case-workflow-update-pending-task.json5, support/v.1.8.0-sprint-22/enhancement-4187-skipping-pending-notice-workflow.json5
=> Enhancement 4187 case stage skip

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> Workflow change - skipping Pending notice and Pending admission hearing

support/v1.8.1-sprint-22.1/4297-task-case-title-script.sql
=> Script to enrich casetitle and caseid in task

backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
=> Set hearing number instead of hearing UUID

common/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java, common/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepository.java, common/egov-filestore/src/test/java/org/egov/filestore/repository/impl/minio/MinioRepositoryTest.java
=> Bug 4312 release

backend/order-management/pom.xml, backend/order-management/src/main/java/pucar/config/Configuration.java, backend/order-management/src/main/java/pucar/config/MainConfiguration.java, backend/order-management/src/main/java/pucar/util/CipherUtil.java, backend/order-management/src/main/resources/application.properties, backend/order-management/src/test/java/pucar/util/CipherUtilTest.java
=> add validation in cipher util

backend/bail-bond/src/main/java/digit/repository/querybuilder/BailQueryBuilder.java
=> left join surety on bail_id

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/web/models/Attendee.java, backend/case/src/main/java/org/pucar/dristi/web/models/Hearing.java, backend/hearing-management/src/main/java/digit/web/models/Attendee.java, backend/hearing-management/src/main/java/digit/web/models/Hearing.java, backend/scheduler-svc/src/main/java/digit/web/models/hearing/Attendee.java, backend/transformer/src/main/java/org/egov/transformer/models/Attendee.java
=> added id and hearing summary

support/v1.9.0-sprint-23/feature-4272-bailbond-mdms-data.json5, support/v1.9.0-sprint-23/feature-4272-pending-task.json5
=> Add mdms support files

backend/openapi/src/main/java/org/pucar/dristi/service/OpenApiService.java
=> setting is active to true (#3843)

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailEsignModal.js
=> updated redirection

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/web/models/Attendee.java, backend/case/src/main/java/org/pucar/dristi/web/models/Hearing.java, backend/hearing-management/src/main/java/digit/web/models/Attendee.java, backend/hearing-management/src/main/java/digit/web/models/Hearing.java, backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java, backend/scheduler-svc/src/main/java/digit/web/models/hearing/Attendee.java, backend/transformer/src/main/java/org/egov/transformer/models/Attendee.java
=> Enriched Attendees id

backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java
=> enriched hearing attendees id

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailUploadSignatureModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/generateBailBondConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondSignaturePage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Fix for Duplication of sureties

backend/bail-bond/src/main/java/digit/enrichment/BailRegistrationEnrichment.java, backend/bail-bond/src/main/java/digit/service/BailService.java
=> Enrich audit details from existing bail upon update

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SuretyComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailBondReviewModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/generateBailBondConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondSignaturePage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Fix for preview all docs

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> maruFix for validation for same mobile number of different surities

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Changes related to fileStore

backend/bail-bond/src/main/java/digit/service/BailService.java
=> setting doc isActive false if not part of payload

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondModal.js
=> updated roles

backend/openapi/src/main/java/org/pucar/dristi/util/FileStoreUtil.java, common/egov-filestore/src/main/java/org/egov/filestore/persistence/repository/ArtifactRepository.java
=> Change implementation to accept module as list

backend/bail-bond/src/main/java/digit/service/BailService.java
=> Add System role on e-sign complete

backend/bail-bond/src/main/java/digit/repository/querybuilder/BailQueryBuilder.java, backend/bail-bond/src/main/java/digit/service/BailService.java, backend/bail-bond/src/main/java/digit/web/models/BailSearchCriteria.java, backend/bail-bond/src/test/java/digit/service/BailServiceTest.java, backend/openapi/src/main/java/org/pucar/dristi/service/OpenApiService.java, backend/openapi/src/main/java/org/pucar/dristi/util/BailUtil.java
=> restrict search

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailBondEsignLockModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Add Validation for Save Draft

backend/bail-bond/src/main/java/digit/config/ServiceConstants.java, backend/bail-bond/src/main/java/digit/validator/BailValidator.java, backend/bail-bond/src/main/java/digit/web/models/Bail.java, backend/bail-bond/src/main/java/digit/web/models/Surety.java
=> Remove unnecessary null checks in Bail and Surety

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Fix for Delete Surety

backend/bail-bond/src/main/java/digit/service/BailService.java, backend/bail-bond/src/test/java/digit/service/BailServiceTest.java
=> sed isactive true doc and fix encryption issue

common/egov-url-shortening/src/main/java/org/egov/url/shortening/repository/UrlDBRepository.java
=> expiring the latest url's

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/Module.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondLinkExpiredPage.js
=> ExpiryPage Redirection fix

backend/bail-bond/src/main/java/digit/enrichment/BailRegistrationEnrichment.java
=> Update Idgen format

common/egov-filestore/src/main/java/org/egov/filestore/repository/impl/minio/MinioRepository.java
=> enhance filestore for size mismatch while downloading

support/v1.9.0-sprint-23/4272-mdms-data-case-bundle.json, utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
=> updated sorting order for case bailbond

utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
=> updated case bundle for bail bond

backend/bail-bond/src/main/java/digit/service/BailService.java
=> added is true

backend/openapi/src/main/java/org/pucar/dristi/service/OpenApiService.java, backend/openapi/src/main/java/org/pucar/dristi/util/BailUtil.java
=> update with main

utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
=> Bug 4358 casebundle main

support/v1.9.0-sprint-23/4272-mdms-data-encrypt-decrypt.json
=> update encr decrytion for surety

backend/bail-bond/src/main/java/digit/config/Configuration.java, backend/bail-bond/src/main/java/digit/config/ServiceConstants.java, backend/bail-bond/src/main/java/digit/service/BailService.java, backend/bail-bond/src/main/java/digit/service/NotificationService.java, backend/bail-bond/src/main/java/digit/util/UserUtil.java, backend/bail-bond/src/main/java/digit/web/controllers/BailApiController.java, backend/bail-bond/src/main/java/digit/web/models/Bail.java, backend/bail-bond/src/main/java/digit/web/models/Email.java, backend/bail-bond/src/main/java/digit/web/models/EmailContent.java, backend/bail-bond/src/main/java/digit/web/models/EmailRecipientData.java, backend/bail-bond/src/main/java/digit/web/models/EmailRequest.java, backend/bail-bond/src/main/java/digit/web/models/EmailTemplateData.java, backend/bail-bond/src/main/resources/application.properties, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/consumer/EmailNotificationListener.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/service/ExternalEmailService.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/service/MessageConstruction.java, common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/utils/Constants.java, common/egov-notification-mail/src/main/resources/application.properties
=> Add mail feature to release

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Payload Fix on bail Type Change

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/util/PaymentCalculaterUtil.java, backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java, backend/scheduler-svc/src/main/java/digit/service/hearing/HearingProcessor.java
=> Updated causeList filter and logs for misc payment during efiling.

backend/bail-bond/src/main/resources/application.properties
=> added sms template id's for bail-bond

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Change the loader type

backend/bail-bond/src/main/java/digit/service/BailService.java
=> fixed e-sign issue

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/generateBailBondConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Fix for Make "Other Documents" field non-mandatory

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondSignModal.js, utilities/dristi-pdf/src/bailBondHandlers/bailBond.js
=> updated place holder

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/generateBailBondConfig.js
=> Add Optional label

backend/bail-bond/src/main/java/digit/config/ServiceConstants.java, backend/bail-bond/src/main/java/digit/service/NotificationService.java, backend/bail-bond/src/main/java/digit/util/DateUtil.java
=> Update date in bail bond signature email

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> Code refractor uat

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/case/src/main/java/org/pucar/dristi/util/PaymentCalculaterUtil.java, backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java, backend/scheduler-svc/src/main/java/digit/service/CauseListService.java, backend/scheduler-svc/src/main/java/digit/service/hearing/HearingProcessor.java, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Hotfix 4371 4335 release

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
=> Add condition to generate cmp number

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java, backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
=> cmpNumber enrichment in update call's

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/GenerateBailBond.js
=> Fix for redirection on refresh

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java, backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
(cherry picked from commit 1ed2b8da83b46c9c27703433410f9b754af2cee4)
=> cmpNumber enrichment in update call's (#4005)

backend/transformer/src/main/java/org/egov/transformer/service/HearingService.java
=> error handling minor fix

common/egov-url-shortening/src/main/java/org/egov/url/shortening/controller/ShortenController.java, common/egov-url-shortening/src/main/java/org/egov/url/shortening/service/URLConverterService.java, common/egov-url-shortening/src/main/resources/application.properties, common/egov-url-shortening/src/test/java/org/egov/url/shortening/controller/ShortenControllerTest.java
=> changes from path variable to request param

backend/bail-bond/src/main/java/digit/config/MainConfiguration.java, backend/bail-bond/src/main/java/digit/config/lombok.config, backend/bail-bond/src/test/java/digit/config/BailEncryptionConfigurationTest.java, backend/bail-bond/src/test/java/digit/config/ConfigurationTest.java, backend/bail-bond/src/test/java/digit/config/MainConfigurationTest.java, backend/bail-bond/src/test/java/digit/config/ServiceConstantsTest.java, backend/bail-bond/src/test/java/digit/enrichment/BailRegistrationEnrichmentTest.java, backend/bail-bond/src/test/java/digit/repository/BailRepositoryTest.java, backend/bail-bond/src/test/java/digit/repository/querybuilder/BailQueryBuilderTest.java, backend/bail-bond/src/test/java/digit/repository/rowmapper/BailRowMapperTest.java, backend/bail-bond/src/test/java/digit/service/BailConvertClassTest.java, backend/bail-bond/src/test/java/digit/service/BailEncryptionServiceImplTest.java, backend/bail-bond/src/test/java/digit/service/NotificationServiceTest.java, backend/bail-bond/src/test/java/digit/service/WorkflowServiceTest.java, backend/bail-bond/src/test/java/digit/util/ByteArrayMultipartFileTest.java, backend/bail-bond/src/test/java/digit/util/CaseUtilTest.java, backend/bail-bond/src/test/java/digit/util/DateUtilTest.java, backend/bail-bond/src/test/java/digit/util/FileStoreUtilTest.java, backend/bail-bond/src/test/java/digit/util/FileValidationUtilTest.java, backend/bail-bond/src/test/java/digit/util/IdgenUtilTest.java, backend/bail-bond/src/test/java/digit/util/IndexerUtilsTest.java, backend/bail-bond/src/test/java/digit/util/MdmsUtilTest.java, backend/bail-bond/src/test/java/digit/util/ResponseInfoFactoryTest.java, backend/bail-bond/src/test/java/digit/util/UserUtilTest.java, backend/bail-bond/src/test/java/digit/util/WorkflowUtilTest.java, backend/bail-bond/src/test/java/digit/validator/BailValidatorTest.java, backend/bail-bond/src/test/java/digit/web/controllers/BailApiControllerTest.java
=> Add test cases for Bail API

support/poa-join-case/4376-enc-dec-mdms-data.json5
=> update encr decrytion for poa respondent

backend/evidence/src/main/java/org/pucar/dristi/repository/rowmapper/EvidenceRowMapper.java
=> Add isEvidenceMarkedFlow field to evidence rowmapper

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
=> Updated logic of delay condonation. (#4034)

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/DocumentsV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDepositionDocModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailEsignModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/submissions/useOpenApiSearchWitnessDeposition.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionLoginPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionSignaturePage.js
=> Feature 4409 update witness

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/DocumentsV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDepositionDocModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailEsignModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/submissions/useOpenApiSearchWitnessDeposition.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionLoginPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionSignaturePage.js
=> Witness dep update

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
* Updated css version
* CSS version upgrade
CSS version upgrade
=> Css upgrade aug 7 develop (#4085)

utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
=> Pdf partyName fix

backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java, backend/evidence/src/main/java/org/pucar/dristi/repository/EvidenceRepository.java
=> correct the assignment of pseudo tag

backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
* Modify condition to update workflow status
* Address coderabbit comments
(cherry picked from commit 9233ca392e90520dea3b55b6a510555eabe5f398)
=> Modify condition to update workflow status (#4098)

backend/openapi/src/main/java/org/pucar/dristi/web/models/witnessdeposition/Artifact.java, backend/openapi/src/main/java/org/pucar/dristi/web/models/witnessdeposition/OpenApiEvidenceResponse.java, backend/openapi/src/test/java/org/pucar/dristi/web/models/witnessdeposition/ArtifactTest.java, backend/openapi/src/test/java/org/pucar/dristi/web/models/witnessdeposition/OpenApiEvidenceResponseTest.java
=> added status and tag in openApi service

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/DocumentsV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/AddWitnessModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionSignaturePage.js
=> Bug [4440, 4435, 4429]  develop

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/AddWitnessModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
https://github.com/pucardotorg/dristi/issues/4432
https://github.com/pucardotorg/dristi/issues/4433
https://github.com/pucardotorg/dristi/issues/4434
=> fixed button disable in witnessModal, add witness fix in order page

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/WitnessDepositionSignModal.js
https://github.com/pucardotorg/dristi/issues/4435
=> fixed Pending Review pending task redirection

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ConfirmDepositionDeleteModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDepositionReviewModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionSignaturePage.js
=> Bug 4229 4441 develop

backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
=> Bug 4448 dev

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js
=> [4451]: ownerType sent in payload for pdf

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js
=> [#4451]: ownerType sent in payload for pdf

backend/scheduler-svc/src/main/resources/application.properties
=> added flag for updating metrics to true

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondSignModal.js, support/v1.9.0-sprint-23/4272-roles-update.txt
=> restricted sign option only to judge

backend/evidence/src/main/java/org/pucar/dristi/util/EsUtil.java
=> Feature 4408 null check index

backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java, support/v1.10.0-sprint-24/4130-mdms-case-filing.json
=> Enhancement 4420 uat

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
=> fix for sender name missing

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> payload fix for task in witness

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
=> fix for task paylod in warrant

backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSummons.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderWarrant.java, backend/order-management/src/main/java/pucar/util/TaskUtil.java
=> skip payment for court witness

backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSummons.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderWarrant.java, backend/order-management/src/main/java/pucar/util/TaskUtil.java
=> Bug 4463 qa

backend/order/src/main/resources/db/migration/main/V20251408113600__order__ddl.sql
=> updated comments character limit

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
=> sentence limit to infinite in Judgement order

support/v1.10.0-sprint-24/4452-mdms-data.json
=> add support folder for e sewa user

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
=> Fix for judge pending task

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js
=> changes for enhancemets [4506, 4509] in UAT

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
=> Updated case Type

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawerV2.js, utilities/dristi-pdf/src/hearingHandlers/witnessDeposition.js
=> changed TextArea to Rich Text Editor for witness deposition

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderSummons.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderWarrant.java
The taskDetails in additionalDetails is coming as a string so mapped it to json string and then to json to extract data from it.
=> cast taskdetails to string instead of json

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/MarkAsEvidence.js
=> updated evidence number format

utilities/dristi-pdf/src/EvidenceHandlers/evidence.js, utilities/dristi-pdf/src/utils/commonUtils.js
=> updated courtname

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/MarkAsEvidence.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> Bug casefile release

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/MarkAsEvidence.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> Bug casefile main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> updated view in bulk mark as evidence

backend/bail-bond/src/main/resources/application.properties, support/v1.10.0-sprint-24/4408-mark-evidence-workflow.json5, support/v1.10.0-sprint-24/4409-mdms-pending-task.json5, support/v1.10.0-sprint-24/4409-user-update.json5, support/v1.10.0-sprint-24/deployment.md, support/v1.10.0-sprint-24/feature-4409-mdms-role-action.json5
=> Bail bond sms template main

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
=> added delete option for witness addresses

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
=> Change Label logic

utilities/dristi-pdf/src/config.js, utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js, utilities/dristi-pdf/src/routes/order.js, utilities/dristi-pdf/src/utils/addressUtils.js, utilities/dristi-pdf/src/utils/orderUtils.js
https://github.com/pucardotorg/dristi/issues/4457
=> new order pdf handler

utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
https://github.com/pucardotorg/dristi/issues/4457
=> added localization in new order pdf

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/DocumentsV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/WitnessDepositionSignModal.js
=> Added Sign option for witness deposition fromm Documents tab

common/inbox/src/main/java/org/egov/inbox/repository/builder/V2/InboxQueryBuilder.java, common/inbox/src/main/java/org/egov/inbox/web/model/SortOrder.java, support/v1.11.0-sprint-25/4492-mdms-data.json5, support/v1.11.0-sprint-25/4492-mdms-schema-change.json5
=> added priority and sorting on filingDate and hearingType

utilities/dristi-pdf/src/applicationHandlers/applicationPoaClaim.js
=> Fix  Application Poa Template

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> css upgrade aug 28

backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java, backend/order/src/main/java/org/pucar/dristi/validators/OrderRegistrationValidator.java, backend/order/src/main/java/org/pucar/dristi/web/models/Order.java, backend/order/src/main/resources/db/migration/main/V20252608113600__order__ddl.sql, backend/order/src/test/java/org/pucar/dristi/validators/OrderRegistrationValidatorTest.java
=> 4457 removed validation

backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java, backend/case/src/main/resources/application.properties, support/v1.11.0-sprint-25/4458-courtcasenumber-script.sql
=> added script and changed sequence of LPR

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js, utilities/dristi-pdf/src/caseBundle/sections/processCourtEvidence.js
https://github.com/pucardotorg/dristi/issues/4541
https://github.com/pucardotorg/dristi/issues/4540
=> Removed save sign Later from A-Diary

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> Removed few orders when case is in lpr qa

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/App.js
https://github.com/pucardotorg/dristi/issues/4539
=> mobile view text changes for whole application

backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
#4538
Removing the condition for null check on mobile numbers to compute the final list of mobile number for the witness. As we do not need to send same mobile number again in payload
=> remove null check for mobile numbers

backend/order-management/src/main/java/pucar/util/TaskUtil.java
=> Modified CourtWitness logic for pending task creation

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondLoginPage.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionLoginPage.js
=> CSS Button Fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> null check for documents while mock esign

utilities/dristi-pdf/src/applicationHandlers/applicationPoaClaim.js
=> Fix related to Revocation of Existing Power of Attorney

utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js, utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
=> fixed download case bundle issue

backend/order/src/main/resources/db/migration/main/V20250209032600__order__ddl.sql
=> Removed limit on description size of dristi_orders

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
https://github.com/pucardotorg/dristi/issues/4477
=> fixed pendingTask redirection for Schedule Hearing

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js, utilities/dristi-pdf/src/orderHandlers/formatDate.js
=> Fix related to add order item, publish order fail

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderUtils.js
=> Fix related to party type and application Number

backend/ab-diary/src/main/java/digit/web/models/CaseDiaryEntry.java, backend/ab-diary/src/main/resources/db/migration/main/V20250309203500__casediary__ddl.sql, backend/application/src/main/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilder.java, backend/application/src/main/java/org/pucar/dristi/web/models/ApplicationCriteria.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/orders/Order.java, backend/order-management/src/main/java/pucar/web/models/Order.java, backend/order-management/src/main/java/pucar/web/models/adiary/CaseDiaryEntry.java, backend/order/src/main/java/org/pucar/dristi/repository/querybuilder/OrderQueryBuilder.java, backend/order/src/main/java/org/pucar/dristi/repository/rowmapper/OrderRowMapper.java, backend/order/src/main/java/org/pucar/dristi/web/models/Order.java, backend/order/src/main/resources/db/migration/main/V20250309113600__order__ddl.sql, backend/transformer/src/main/java/org/egov/transformer/models/Order.java
=> enable fuzzysearch in application, botd limit removed, added scheduleHearingNumber in order

frontend/micro-ui/web/micro-ui-internals/example/public/index.html, frontend/micro-ui/web/micro-ui-internals/package.json, frontend/micro-ui/web/micro-ui-internals/packages/css/package.json, frontend/micro-ui/web/package.json, frontend/micro-ui/web/public/index.html
=> Css upgrade sept 3 develop

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderUtils.js
=> Added some new form field

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js, utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
https://github.com/pucardotorg/dristi/issues/4576
https://github.com/pucardotorg/dristi/issues/4557
https://github.com/pucardotorg/dristi/issues/4558
=> added richText in itemText, added scheduledHearingNumber

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderApiCallUtils.js
=> fixed orderTitle issue

backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderAttachment.java, backend/order-management/src/main/java/pucar/strategy/ordertype/PublishOrderProclamation.java, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
=> Removed-lpr-changes and UI localisation

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
=> Parties tab tooltip fixed

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customTextArea.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js, utilities/dristi-pdf/src/utils/htmlToFormattedText.js
=> fixed itemText box, added NextHearingDate new logic, fixed schedulingHearingNumber

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EditSendBackModal.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
https://github.com/pucardotorg/dristi/issues/4556
=> added delete draft functionality for new orders

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> Add CaseNumber in UpdateOrder

backend/order-management/src/main/java/pucar/config/Configuration.java, backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/service/CompositeOrderService.java, backend/order-management/src/main/java/pucar/strategy/common/PublishOrder.java, backend/order-management/src/main/java/pucar/util/HearingUtil.java, backend/order-management/src/main/java/pucar/util/LocalizationUtil.java, backend/order-management/src/main/java/pucar/util/OrderUtil.java, backend/order-management/src/main/resources/application.properties, backend/order/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java, backend/order/src/main/java/org/pucar/dristi/service/SmsNotificationService.java, backend/order/src/main/java/org/pucar/dristi/util/LocalizationUtil.java, backend/order/src/main/resources/application.properties
=> localization changes

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
=> Suggested Changes Fix

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
=> Remove the Brief Summary of Withdrawal

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> fixed mandatory field issue in attendees in order

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
=> added action field for functional specs -advocate replacement request

backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java, backend/order/src/main/java/org/pucar/dristi/web/models/RemoveItem.java
=> item text update on remove item

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js, utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
https://github.com/pucardotorg/dristi/issues/4613
https://github.com/pucardotorg/dristi/issues/4633
=> added new order template change, fixed nextHearing button logic, fixed autosaving in order

backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java
=> Bug fix in witness validation

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js, support/v1.11.0-sprint-25/4313-mdms-data.json, support/v1.11.0-sprint-25/4457-order-mdms-data.json
=> Cherry pick to release25

backend/order-management/src/main/java/pucar/util/OrderUtil.java
=> remove next hearing details from transcript

backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java
=> Fix validateEmail logic for witness

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
=> Fixed line break in Adiary

backend/order-management/src/main/java/pucar/util/OrderUtil.java, backend/transformer/src/main/java/org/egov/transformer/event/impl/OrderImpl.java
=> remove absent from botd if empty

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> Remove disabling of bailbond when skip hearing

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
Instead of casting existing witness JsonNode to WitnessDetails class and updating individual fields, cast updated WitnessDetails object to JsonNode and set it in the existing witness node
=> Modify witness update logic inside case additional details

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
=> Remove Attendees  bar from transcript modal

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> Enable attendee when all selected absent

backend/order-management/src/main/java/pucar/util/HearingUtil.java
=> remove hearing summary for inprogress hearing

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java, backend/order-management/src/main/java/pucar/config/ServiceConstants.java, backend/order-management/src/main/java/pucar/service/OrderService.java, backend/order-management/src/main/java/pucar/util/HearingUtil.java, backend/order-management/src/main/java/pucar/util/OrderUtil.java, backend/transformer/src/main/java/org/egov/transformer/config/ServiceConstants.java, backend/transformer/src/main/java/org/egov/transformer/event/impl/OrderImpl.java
=> Main to develop changes

backend/hearing/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/hearing/src/main/java/org/pucar/dristi/util/OrderUtil.java
=> Hotfix order draft uat

frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/reviewsummons.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BulkCheckbox.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Bulk actions

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
=> Fix for clear the hearing date on clik on skipScheduling

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
=> remove dash in hearing time

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> show dca when in pending/review

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
=> bugfix for proclamation task

backend/hearing/src/main/java/org/pucar/dristi/util/OrderUtil.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/orders/OrderCriteria.java, backend/order/src/main/java/org/pucar/dristi/repository/querybuilder/OrderQueryBuilder.java, backend/order/src/main/java/org/pucar/dristi/web/models/OrderCriteria.java
=> Bug 4689 expiry issue fix main

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
=> multiple dca can be raised

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
issue: https://github.com/pucardotorg/dristi/issues/4690
=> [4690]: checked mandatory validation on  submit

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
issue: https://github.com/pucardotorg/dristi/issues/4690
=> [4690 release]: checked mandatory validation on submit

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Updated payload with applicationStatus for tab change

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
=> release fix- added check for null actions on view case screen on citizen login

support/v1.12.0-sprint-26/feature-4623-new-role-actions.json5, support/v1.12.0-sprint-26/feature-4623-new-roles.json5
=> Update support folder

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Task editor role for send and update

backend/hearing/src/main/java/org/pucar/dristi/config/ServiceConstants.java, backend/hearing/src/main/java/org/pucar/dristi/kafka/consumer/HearingUpdateConsumer.java, backend/hearing/src/main/java/org/pucar/dristi/util/OrderUtil.java, backend/hearing/src/main/java/org/pucar/dristi/util/PendingTaskUtil.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/cases/CaseOutcome.java, backend/hearing/src/main/java/org/pucar/dristi/web/models/cases/Outcome.java, backend/hearing/src/main/resources/application.properties, backend/order/src/main/java/org/pucar/dristi/repository/querybuilder/OrderQueryBuilder.java
* Fixed Schedule hearing PT for dismissed case.
* Minor fix
* added missing question mark
* Removed redundent code
* no need to change order management.
* 4689 bug fix
* Minor bug
---------
(cherry picked from commit 8c9cd074ea7595181b876aeb765525e24596da50)
=> Removed Dismissed case from schedul hearing action filter (#4591)

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
=> fix delay condonation label

common/inbox/src/main/java/org/egov/inbox/service/V2/InboxServiceV2.java, common/inbox/src/main/java/org/egov/inbox/web/model/Criteria.java
=> Feature 4623 qa

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
=> Sending POST in payload instead of EPOST

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeSidebar.js
=> VIEW_SIGN_PROCESS role removal

frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/OfflinePaymentsHomeTab.js, frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/RegisterUsersHomeTab.js
=> css changes in dropdown for offline payments, register users

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Signed popup changed and bulk sign condition added

backend/summons-svc/src/main/java/digit/config/Configuration.java, backend/summons-svc/src/main/java/digit/config/ServiceConstants.java, backend/summons-svc/src/main/java/digit/service/DemandService.java, backend/summons-svc/src/main/resources/application.properties, backend/treasury-backend/src/main/java/org/egov/eTreasury/service/PaymentService.java
=> added single demand creation logic for epost

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
=> disabled hearing button if hearing is not in progress

support/v1.12.0-sprint-26/feature-4623-new-role-actions.json5
=> Add role action mappings

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
=> Bulk download after bulk sign
