pucardotorg/dristi-solutions

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/admission/CustomSubmitModal.js

Fixed the bug

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

Added judge role as well so that the comment component will be visible to judge

Added judge role

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js

changed filestoreId for order review modal (testing purpose)

changed filestoreId for order review modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/MarkAttendance.js

enable mark attendance in hearing

enable mark attendance in hearing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js

Don't show Hearing in optout state as next hearing

Bug Fix Related To Optout

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js

Fixed next hearing modal UI

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/fileStoreUtil.js

FileStoreId chnage for UAT in fileStoreUtils

FileStoreUtilUpdate

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ApplicationInfoComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js

pendingTask close in ScheduleHearing, some css change

pendingTask close in ScheduleHearing, some css change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js

enable view hearings even if no hearings scheduled for the day. 
https://github.com/pucardotorg/Dristi_kerala/issues/1022

enable view hearings even if no hearings scheduled for the day

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js

Sept Demo | Localisation Changes
https://github.com/pucardotorg/Dristi_kerala/issues/1016

Sept Demo Localization changes

---

backend/task/src/main/java/org/pucar/dristi/config/Configuration.java
backend/task/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
backend/task/src/main/java/org/pucar/dristi/validators/TaskRegistrationValidator.java
backend/task/src/main/resources/application.properties

Cherry picked the changes. Please check once @Ajith-beehyv

Task notice bnss

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

View case file changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

Denial of Upadate Api Call in Efiling when it is in correction State

Denial of Upadate Api Call in Correction

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js

Bug fix for styling changes. issue 2 fixes.
https://github.com/orgs/pucardotorg/projects/1/views/17?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C85952217%2C85952228%2C133599386%5D&layout=table&sliceBy%5BcolumnId%5D=Status&filterQuery=label%3A%22Demo+23rd+Sept%22++sham&sliceBy%5Bvalue%5D=To+Do&pane=issue&itemId=80318651

Uat issue with styling of modal , fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

The scheduler is suggesting dates on weekends to the judge during hearing scheduling 
https://github.com/pucardotorg/dristi/issues/1700

show net hearing dates from availibility api call

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/RegisterRespondentForm.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

- localisation and validation fix bnss join case
- remove additional details dependency from complainantDetails and advocateDetails

localisation and bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

join case advocate role issue fixed

join case advocate role issue fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js

fix in challan api to send name and number

fix in challan api to send name and number

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

changes for the raised bug 
https://github.com/pucardotorg/dristi/issues/1699

styling changes for scroll

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

usertype select bug fixed uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js

[#1709](https://github.com/pucardotorg/dristi/issues/1709)

transcript css change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CorrectionsSubmitModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

The changes in the date of info text in summons modal

Summon modal fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

court staff pending-task of summon fix redirect fix

court staff pending-task of summon fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js

Removal of download All link and Invalid name pattern fix

Removal Of Download All Link and Invalid name fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js

https://github.com/pucardotorg/dristi/issues/1722 https://github.com/pucardotorg/dristi/issues/1721 https://github.com/pucardotorg/dristi/issues/1719

document owner and visibility fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

not letting efile if generate pdf fails . To fix the issue.
https://github.com/pucardotorg/dristi/issues/1716

not letting efile if generate pdf fails .

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

Fix for p1 issue in 
https://github.com/pucardotorg/dristi/issues/1740

scrutiny checklist

---

.github/workflows/Image-build-summons-svc.yaml
backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/main/java/digit/web/models/Task.java

* handle document null condition.
* some changes.
* Update Image-build-summons-svc.yaml
---------

handle document null condition. (#346)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/index.js

For now The payment breakup will come only for e filing payment. Rest all will just show the amount , that is being fetched from bill api.

Offline App Payment

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js

added judgeId, courtId, benchId fields in the payload of search, update apis of case and hearing

Case hearing payload fixes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Enabling fields for tomorrow's demo. Would work on it once Tahera provides fields in functional specs

Enabling fields transfer order

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/index.js

Develop Changes to uat related to epoc time conversion

Epoc Time Conversion

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js

Fix for payment issue from pending task for e-filing BUG-19
The demand generate was being called when we pay online from a pending task . But it's not needed since it's demand is generated once in E-filing. So have to remove it .Also removed the bill search api that was being used to decide whether to call demand generate or not.

Fix for payment issue from pending task for e-filing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js

https://github.com/pucardotorg/dristi/issues/1808

creating draft in progress pending task after generating order notice

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js

Added extra check after completion of esign in orders and submission
https://github.com/pucardotorg/dristi/issues/1829

Added extra check after completion of esign in orders and submission

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js

https://github.com/pucardotorg/dristi/issues/1831

Court Fee amount showing as 0  bug fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersService.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

- localisation bug #1823
- fullname undefined bug fixed
- notice failure count bug

Uat bug fix nitish

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

added field in task payload

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

1. Hiding "Extension of submission deadline" button on published order preview modal if there already exists a submission made by the respective party on the same order which is not in "Completed", "DELETED", "REJECTED","ABATED" state.
2. On nth application for extension of submission deadline, fetching latest order for extension of deadline and fetching the new submission date from it.

hiding extension of submission deadline button

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LanguageSelection.js

https://github.com/pucardotorg/dristi/issues/1832
https://github.com/pucardotorg/dristi/issues/1833

logo change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

addedd witness details in create task and Split sentence in Advocate Verification step bug

Create task additional field added

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

bailableAmount property name fix and warrant action fix

bailableAmount property name fix and warrant action fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

modified the file name in summons and notice in summons and notice as order type is not their in documents i am using task type as the document name.

modified the file name in summons and notice

---

backend/advocate/src/main/java/org/pucar/dristi/web/controllers/AdvocateApiController.java
backend/case/src/main/resources/application.properties
backend/order/src/main/resources/application.properties

removed advocate from endpoints

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LanguageSelection.js

#1910 , reduced size of unselected language text size

reduced size of unselected language text size

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js

Fix for 
https://github.com/pucardotorg/dristi/issues/1914

1914 bug the close button is hidden behind the top bar

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LanguageSelection.js

updated the font size of select language text

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

https://github.com/pucardotorg/dristi/issues/1931
https://github.com/pucardotorg/dristi/issues/1939
https://github.com/pucardotorg/dristi/issues/1948
https://github.com/pucardotorg/dristi/issues/1951

UAT bugs 1931, 1939, 1948, 1952 fixes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js

Fixes for https://github.com/pucardotorg/Dristi_kerala/issues/1139 and https://github.com/pucardotorg/dristi/issues/1953

payload changes in court staff for api "/task/v1/table/search" and Fix for hiding top bar when modal is open.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

Scrutiny Bug fix - hiding flag icon if Document uploaded in prayer and sworn

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js

https://github.com/pucardotorg/dristi/issues/1914 https://github.com/pucardotorg/dristi/issues/1932 https://github.com/pucardotorg/dristi/issues/1953 https://github.com/pucardotorg/dristi/issues/1955

css overlapping changes and localization in header changes in view case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

https://github.com/pucardotorg/dristi/issues/1942
https://github.com/pucardotorg/dristi/issues/1943
https://github.com/pucardotorg/dristi/issues/1961
https://github.com/pucardotorg/dristi/issues/1931

bugs 1942, 1943, 1961, 1931(breaking and error after generate order)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useApplicationDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js

Reverts pucardotorg/dristi-solutions#569
as requirements are no longer stable and will be revised next sprint

Revert "delay Condonation api added"

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js

https://github.com/pucardotorg/dristi/issues/1942
https://github.com/pucardotorg/dristi/issues/1943

[UAT 1942, 1943]document type fixed in success modal 

---

backend/dristi-case-pdf/service/caseService.js

[pucardotorg#1941](https://github.com/pucardotorg/dristi/issues/1941)

case-pdf Bugs fix (1941)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js

https://github.com/pucardotorg/dristi/issues/1957

removing aadhar auto verify button in e filing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js

https://github.com/pucardotorg/dristi/issues/1994

Replace 'Issue Order' with 'Issue Notice'

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

option to close Pop without issuing the order for notice by adding cross on top right hand corner.
https://github.com/orgs/pucardotorg/projects/1/views/3?filterQuery=utpal&pane=issue&itemId=82923399&issue=pucardotorg%7Cdristi%7C1989

Option to close pop up

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js

https://github.com/pucardotorg/dristi/issues/2009

unknown respondent issue and partyName breakage fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js

https://github.com/pucardotorg/dristi/issues/1977

save deposition button disable fix

---

backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java

[pucardtorg#1902](https://github.com/pucardotorg/dristi/issues/1902#issuecomment-2410549348)

summons and notice pdf issue.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js

https://github.com/pucardotorg/dristi/issues/1902 https://github.com/pucardotorg/dristi/issues/2020

schedule hearing break fix, sending docSubType in summons and notice

---

backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
backend/application/src/main/java/org/pucar/dristi/util/CaseUtil.java
backend/application/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
backend/application/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
backend/application/src/main/resources/application.properties
backend/application/src/test/java/org/pucar/dristi/util/CaseUtilTest.java

application number enrichment by cmp number on submission approval

application number enrichment by cmp number on submission approval

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

resolved issue if second name is not present showing null in name

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js

https://github.com/pucardotorg/dristi/issues/2030

parties page break fix in view case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js

Fix for
**https://github.com/pucardotorg/dristi/issues/1972**

Localization missing in OCR error

---

common/collection-services/src/main/java/org/egov/collection/config/ApplicationProperties.java
common/collection-services/src/main/java/org/egov/collection/util/PaymentValidator.java
common/collection-services/src/main/java/org/egov/collection/util/Utils.java
common/collection-services/src/main/resources/application.properties

https://github.com/pucardotorg/dristi/issues/2040

bugs -2040 collection service added a flag for fractional payment

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js

resolved bug - sending wrong tasktype in calculate for sms api

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js

https://github.com/pucardotorg/dristi/issues/2130

Order Status is wrong if box is closed in QA

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js

https://github.com/pucardotorg/dristi/issues/1963

removed raise application button in overview, enable Complaint tab

---

common/inbox/pom.xml

updated pom.xml according to scan code alerts

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js

https://github.com/pucardotorg/dristi/issues/2078
https://github.com/pucardotorg/dristi/issues/2130

Bug #2078 #2130

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/hearingWorkflow.js
utilities/dristi-pdf/src/config.js
utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js

https://github.com/pucardotorg/dristi/issues/2141 https://github.com/pucardotorg/dristi/issues/2142

[bug- 2142]: Internal Server Error while Order Signing (OPTOUT -> OPT_OUT)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js

CSS Issue in Submit button #1938

CSS Issue in Submit button #1938

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/MakeSubmissionBailConfig.js

https://github.com/pucardotorg/dristi/issues/2121

bounced cheque to dishonored cheque

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

fixed null name property when concatenating them #2139

Bug 2139 name null fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/E-PostTrackingConfig.js

bug -#2133 localization issue

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/2174

added Individual condition in typeOfEntity

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js

https://github.com/pucardotorg/dristi/issues/2132

[Bug 2132]

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js

https://github.com/pucardotorg/dristi/issues/2166

[bug 2166 QA] removed repeating error message on pincode

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/hearingWorkflow.js

https://github.com/pucardotorg/dristi/issues/2018
https://github.com/pucardotorg/dristi/issues/2222

[BUG 2018 QA ] filtering out hearings with status "ABATED"

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Amount Paid shown is In-Correct in Court Staff User #2136
css issue #2220

Amount Paid shown is In-Correct in Court Staff User fixed and css issue fixed Bug 2136

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ApplicationInfoComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js

https://github.com/pucardotorg/dristi/issues/2226

Epost fees and recieved date In-correct fix

---

backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java

[pucardtorg#2217](https://github.com/pucardotorg/dristi/issues/2217)

fix sbi-transaction issue.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

https://github.com/pucardotorg/dristi/issues/2156#event-14760800228

Change to not show a case in judge if in draft state

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/components/OtpComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/RegisterRespondentForm.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OTPInput.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js

fixed ui of otp modal and other minor ui fix, bug #1938

fixed ui of otp modal and other minor ui fix, bug #1938

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js

https://github.com/pucardotorg/dristi/issues/2235

Localization changes in NextHearingCard

---

backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java

[pucardtorg#2164](https://github.com/pucardotorg/dristi/issues/2164)

summons,notice,warrant pdf fixes.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/2258

case Tittle name update after Correction

---

backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/controller/IcopsController.java
backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/LocationBasedJurisdictionResponse.java
backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/LocationRequest.java
backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/service/IcopsService.java
backend/icops_integration-kerala/src/test/java/com/egov/icops_integrationkerala/service/IcopsServiceTest.java

[pucarddtorg#1981](https://github.com/pucardotorg/dristi/issues/1981)

create location-based-jurisdiction api.

---

backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/config/SecurityConfig.java

[pucardtorg#1981](https://github.com/pucardotorg/dristi/issues/1981)

added location-based api in security config.

---

backend/summons-svc/src/main/java/digit/config/Configuration.java
backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
backend/summons-svc/src/main/java/digit/util/IcopsUtil.java
backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/main/java/digit/web/models/Location.java
backend/summons-svc/src/main/java/digit/web/models/LocationBasedJurisdiction.java
backend/summons-svc/src/main/java/digit/web/models/LocationBasedJurisdictionResponse.java
backend/summons-svc/src/main/java/digit/web/models/LocationRequest.java
backend/summons-svc/src/main/java/digit/web/models/PoliceStationDetails.java
backend/summons-svc/src/main/resources/application.properties
backend/summons-svc/src/test/java/digit/util/IcopsUtilTest.java

[pucardtorg#1981](https://github.com/pucardotorg/dristi/issues/1981)

getting warrant executor name from icops.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

https://github.com/pucardotorg/dristi/issues/1999

bugFix on Reschedule Admission Hearing visible on reschedule

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

https://github.com/pucardotorg/dristi/issues/1887
Also added for notice via post

addition of text in summon and notice modal

---

backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
backend/case/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilderTest.java

added caseSearchText to filter based on cmpnumber,filingnumber,courtcasenuumber

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js

bug -2241 change in bar registration validation

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss

bug -1979 css issue in file upload

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

marking error as error even if it's same as prev error

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

bug -1974 marking error as error even if it's same as prev error

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/2275

Front end change to call new end point of case complaint pdf

---

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/case/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

https://github.com/pucardotorg/dristi/issues/2274

Feature 2274 case search temporary fix patch

---

common/individual/postman/Individual-postman-collecttion.json
common/individual/src/main/resources/application.properties

Enhance 2296

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js

https://github.com/pucardotorg/dristi/issues/2223 https://github.com/pucardotorg/dristi/issues/2282

adding courtId only if not in draft stage

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js

Fix for https://github.com/pucardotorg/dristi/issues/2323

Upload ID Proof field is to accept the jpeg format

---

backend/summons-svc/src/main/java/digit/config/Configuration.java
backend/summons-svc/src/main/java/digit/service/SummonsService.java
backend/summons-svc/src/main/resources/application.properties
backend/summons-svc/src/test/java/digit/service/SummonsServiceTest.java

[#pucardtorg2260](https://github.com/pucardotorg/dristi/issues/2260)

Added one user role to update the workflow.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js

added info note box for cause list download btn

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js

dependent fields, mark same error in scrutiny

---

backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java

[pucardtorg#2154](https://github.com/pucardotorg/dristi/issues/2154)

enable reverification sbi api.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js

updated hard coded string with localized codes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

updated link for  Section 138 link in E Filing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js

https://github.com/pucardotorg/dristi/issues/2352

[BUG 2352]: [DPG-DEV | Schedule Hearing button should be disabled in Court Staff user

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/public/index.html

added latest CSS style-sheet link

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js

changes for https://github.com/pucardotorg/dristi/issues/2374

CASE_CREATOR & CASE_EDITOR Roles are not mandaotry for Nyay-Mitra

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js

Conditional - Action column in summons, notice, warrants payment

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js

https://github.com/pucardotorg/dristi/issues/2383

hide map functionality and autofilling of details in location

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

https://github.com/pucardotorg/dristi/issues/2300

Show Option to Reschedule Hearing for Schedule Only

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

https://github.com/pucardotorg/dristi/issues/2304

disabling all button in evidence modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js

https://github.com/pucardotorg/dristi/issues/2370

removed flag from advocateIdProof

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSortComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/PaymentInbox.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js

updated hard coded strings

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/SummaryModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/ReschedulingPurpose.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersHome.js

https://github.com/pucardotorg/dristi/issues/2279

sending null in createdDate in GenerateOrder

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js

https://github.com/pucardotorg/dristi/issues/2281

Some words are missing in Malayalam in Judge login

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Case dependecy remove from nayamitra payment page

Case dependecy remove from nayamitra payment page

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js

https://github.com/pucardotorg/dristi/issues/2279

in orders tab createdTime -> createdDate

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomDetailsCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/Response.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/HearingSideCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js

https://github.com/pucardotorg/dristi/issues/2261

Localization [some words are missing in Malayalam] in efiling

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

* remove case dependency from nayamitra view payment details page
* added paymentdatails dependency in key of search bill api

Case dependecy remove from nayamitra payment page (#910)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js

removed default filetype which was pdf and made generic
https://github.com/pucardotorg/dristi/issues/2397

removed default filetype which was pdf and made generic

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js

Add ADVOCATE_VIEWER role to litigant and advocate clerk
Add ADVOCATE_APPLICATION_VIEWER role to advocate users
Only user with ADVOCATE_APPLICATION_VIEWER should have access to advocate details page

Adding new roles to litigant, advocate_clerk and advocat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js

changes made: added auth token in headers
https://github.com/pucardotorg/dristi/issues/2397

[Bug 2397]: Nyaymitra user is not able to download file, throwing authentication error

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OTPInput.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js

#1228
Replacing text OTP with box OTP component

replacing with otp component

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js

Add ADVOCATE_VIEWER role to litigant and advocate clerk
Add ADVOCATE_APPLICATION_VIEWER role to advocate users
Only user with ADVOCATE_APPLICATION_VIEWER should have access to advocate details page

Adding new roles to litigant, advocate_clerk and advocate

---

common/egov-filestore/src/main/java/org/egov/filestore/config/FileStoreConfig.java
common/egov-filestore/src/main/java/org/egov/filestore/validator/StorageValidator.java
common/egov-filestore/src/main/resources/application.properties

validations for currupt files

---

common/pdf-service/src/index.js

https://github.com/pucardotorg/dristi/issues/2266

Adding malayam fo default mapping

---

backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java

[#pucardtorg2408](https://github.com/pucardotorg/dristi/issues/2408)

 fix case registration validation issue

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js

https://github.com/pucardotorg/dristi/issues/2151

Define proper error page and error message

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

updated css for advocate continue button styling

---

common/pdf-service/src/utils/directMapping.js

https://github.com/pucardotorg/dristi/issues/2410

allow apostrophe in object for case pdf change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js

changes made: added auth token in headers
https://github.com/pucardotorg/dristi/issues/2397

[Bug 2397]: Nyaymitra user is not able to download file, throwing authentication error hotfix 0.5

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

* join case enhancement feature #2387
* Complainant Advocate - Add advocate silently
Accused - Confirm Notice/Summons receipt - to exist
* css and minor changes
* fixed update hearing list and dev tested
* code rabbit changes

Join case new enhancement to release

---

backend/dristi-case-pdf/controller/caseController.js
backend/dristi-case-pdf/service/fileService.js
backend/dristi-case-pdf/util/errorUtils.js

Trying to fetch bytesdata using filestoreId and whenever it fails, throwing custom DocumentError

throwing appropriate error whenever file is corrupted

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadSignatureModal.js

displaying error in upload signature when file limit exceeds

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

ocr bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

added await to creatependingtask function

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

https://github.com/pucardotorg/dristi/issues/2420
https://github.com/pucardotorg/dristi/issues/2421

localisation missing on judge and courtstaff

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js

- button un-Clickable resolve in viewCase in order and Submission tab

Bug missed localisation dristi

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/App.js

added a error msg when screen width is less than 900

---

backend/dristi-case-pdf/service/caseService.js
common/pdf-service/src/utils/directMapping.js

added array condition in datamapping, added empy documentList condition

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

same day hearing joining bug fixed #1993

same day hearing joining bug fixed #1993

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js

Pending task closed fix feature #2032

Pending task closed fix feature #2032

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/1964

removing temp testing variable

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomInput.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectBulkInputs.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js

Missed loaclisation

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js

add jpeg file formate
pending response bug fixed

Pending response bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js

https://github.com/pucardotorg/dristi/issues/2431

[bug 2431 update]getting token access inside function call

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js

https://github.com/pucardotorg/dristi/issues/2431

[bug 2431 update] getting token access inside function call

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/1964

adding complaint pdf in documents

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

https://github.com/pucardotorg/dristi/issues/2427

case search not getting called first time fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileUpload.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPaymentResponse.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentRes.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js

#2394 hot fix for the auth token

Hot fix/0.5 for adding auth token in  headers for filstore/ id api

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Fixed redirection issue in courtstaff

Fixed redirection issue in courtstaff

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Fixed redirection issue in courtstaff

Fixed redirection issue in courtstaff (#1036)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

updated hard coded string court staff

updated hard coded string court staff

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

https://github.com/pucardotorg/dristi/issues/2401

view case pdf not shown in esign fix

---

backend/dristi-case-pdf/service/caseService.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

changed docType of complaint pdf, added phone number for advocate, .join fix in pdf-service

---

backend/dristi-case-pdf/service/caseService.js

taking first element for docs

---

backend/dristi-case-pdf/service/caseService.js
backend/dristi-case-pdf/service/fileService.js

aading complainantIdProof in docs

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorBoundaries.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

fixed bug #2174 and make error page responsive and enhance ui #2151

fixed bug #2174 and make error page responsive and enhance ui #2151

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js

Fixed bug #2439 (Views of requests for Advocate clerk is blank)

Fixed bug #2439 (Views of requests for Advocate clerk is blank)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Bug 2382 qa

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Bug 2382 uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

aadded auth token in case print case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

added auth token in case print case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js

updated hard coded strings with localization codes

---

backend/dristi-case-pdf/service/fileService.js

image scaling fix in dristi-case pdf

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js

Witness Deposition download bug fix

---

backend/dristi-case-pdf/service/caseService.js

complainant entity companyName bug

---

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java
backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/case/src/main/java/org/pucar/dristi/scheduling/CronJobScheduler.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/case/src/main/java/org/pucar/dristi/service/IndividualService.java
backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
backend/case/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/case/src/main/java/org/pucar/dristi/util/AdvocateUtil.java
backend/case/src/main/java/org/pucar/dristi/web/models/SmsTemplateData.java
backend/case/src/main/resources/application.properties
backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java

ir is addressing sms-template 2,3,4,5,6,7,8,9,89

sms-template implementation in case service.

---

backend/advocate/src/main/java/org/pucar/dristi/config/Configuration.java
backend/advocate/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/advocate/src/main/java/org/pucar/dristi/service/AdvocateService.java
backend/advocate/src/main/java/org/pucar/dristi/service/IndividualService.java
backend/advocate/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/advocate/src/main/java/org/pucar/dristi/util/IndividualUtil.java
backend/advocate/src/main/java/org/pucar/dristi/web/models/SMSRequest.java
backend/advocate/src/main/java/org/pucar/dristi/web/models/SmsTemplateData.java
backend/advocate/src/main/resources/application.properties
backend/advocate/src/test/java/org/pucar/dristi/service/AdvocateServiceTest.java

sms-template implementation in advocate service.

---

backend/analytics/pom.xml
backend/analytics/src/main/java/org/pucar/dristi/config/Configuration.java
backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/analytics/src/main/java/org/pucar/dristi/repository/ServiceRequestRepository.java
backend/analytics/src/main/java/org/pucar/dristi/service/IndividualService.java
backend/analytics/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/analytics/src/main/java/org/pucar/dristi/util/AdvocateUtil.java
backend/analytics/src/main/java/org/pucar/dristi/util/CaseUtil.java
backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/analytics/src/main/java/org/pucar/dristi/util/IndividualUtil.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/Advocate.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/AdvocateListResponse.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/AdvocateSearchCriteria.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/AdvocateSearchRequest.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/IndividualSearch.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/IndividualSearchRequest.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/SMSRequest.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/SmsTemplateData.java
backend/analytics/src/main/resources/application.properties

2388 analytics service sms template

---

backend/order/pom.xml
backend/order/src/main/java/org/pucar/dristi/config/Configuration.java
backend/order/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/order/src/main/java/org/pucar/dristi/service/IndividualService.java
backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java
backend/order/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/order/src/main/java/org/pucar/dristi/util/AdvocateUtil.java
backend/order/src/main/java/org/pucar/dristi/util/CaseUtil.java
backend/order/src/main/java/org/pucar/dristi/util/IndividualUtil.java
backend/order/src/main/java/org/pucar/dristi/web/models/Advocate.java
backend/order/src/main/java/org/pucar/dristi/web/models/AdvocateListResponse.java
backend/order/src/main/java/org/pucar/dristi/web/models/AdvocateSearchCriteria.java
backend/order/src/main/java/org/pucar/dristi/web/models/AdvocateSearchRequest.java
backend/order/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
backend/order/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
backend/order/src/main/java/org/pucar/dristi/web/models/CourtCase.java
backend/order/src/main/java/org/pucar/dristi/web/models/IndividualSearch.java
backend/order/src/main/java/org/pucar/dristi/web/models/IndividualSearchRequest.java
backend/order/src/main/java/org/pucar/dristi/web/models/SMSRequest.java
backend/order/src/main/java/org/pucar/dristi/web/models/SmsTemplateData.java
backend/order/src/main/resources/application.properties

it is addressing template-104,151

sms-template implementation in order service.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

change stateSla for all pending task #2444

change stateSla for all pending task

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

dueDate to duedate change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

response deadline date bug fixed

response deadline date bug fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Bug 2444 hotfix to release

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Bug 2444 hotfix to develop

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js

fixed bug #2437

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

not calling update casedetials api when issue notice is clicked

Case update API calls in order page

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

User able to add the only spaces as the Comments #2495

remove extra space from comments #2495

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/components/OtpComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js

Otp resend fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

delay condonation and case register to admit flow working #2491

delay condonation and case register to admit flow working

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCheckBoxCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js

css fixed in terms and condition and reschedule hearing modal

css fixed in terms and condition and reschedule hearing modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
utilities/dristi-pdf/src/config.js

https://github.com/pucardotorg/dristi/issues/2512

Changed hard coded judgeName to get from configs

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

resolved issue overlapping on the pending tasks

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js

Auto default city KL fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js

https://github.com/pucardotorg/dristi/issues/2249

amount incorrect shown fix in Nyaymitra

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/2535

remove _generatePdf call from Efiling cases

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/advocateDetailsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

fir for https://github.com/pucardotorg/dristi/issues/2507

During e-filling, a complainant can specify - "Number of Advocates" .

---

backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java

added space in billing format

---

utilities/dristi-pdf/src/config.js
utilities/dristi-pdf/src/orderHandlers/orderNotice.js
utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
utilities/dristi-pdf/src/orderHandlers/summonsIssue.js

https://github.com/pucardotorg/dristi/issues/2540

added orderHeading and designationHeader in config

---

backend/treasury-backend/src/main/java/org/egov/eTreasury/config/PaymentConfiguration.java
backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
backend/treasury-backend/src/main/resources/application.properties

updated the hardcoded challan amount to get it from application.properties

challan amount

---

utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
utilities/dristi-pdf/src/orderHandlers/adrCaseReferral.js
utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
utilities/dristi-pdf/src/orderHandlers/caseTransfer.js
utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
utilities/dristi-pdf/src/orderHandlers/orderSection202crpc.js
utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js

https://github.com/pucardotorg/dristi/issues/2540

other orders changes for orderHeading and judgeDesignation

---

backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/config/Configuration.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/config/ServiceConstants.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/util/CaseUtil.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/CaseCriteria.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/CaseSearchRequest.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/EFillingCalculationCriteria.java
backend/payment-calculator-svc/src/main/resources/application.properties
backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/CaseFeeCalculationServiceTest.java

payment calculation for case for no of advocates

---

backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
backend/summons-svc/src/main/java/digit/service/DemandService.java
backend/summons-svc/src/main/java/digit/web/models/Demand.java

setting billExpiryTime to two years while creating demand

added billExpiryTime in demand object

---

.github/workflows/Image-build-Payment-calculator.yaml
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/channels/EPostFeeService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/channels/EmailFeeService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/channels/PoliceFeeService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/channels/RPADFeeService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/channels/SmsFeeService.java

round off all amount to next integer

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/Header.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/LanguageSelection/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js

Addition of Kollam as city and Kerala as state

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js

level 1 to level 2 change

---

backend/dristi-case-pdf/controller/caseController.js

https://github.com/pucardotorg/dristi/issues/2588

throwing error when Filing number is not present in complaintPdf

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js

fix for https://github.com/pucardotorg/dristi/issues/2551

add flag check for registering advocate after rejection by nyay mitra

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js

E sign enabled prod and change redirect link

E sign enabled prod and change redirect link

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js

sending judgeid, benchid, courtid only when FSO performs VALIDATE action

sending judgeid, benchid, courtid only when FSO performs VALIDATE action

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

added scrollbar in complaint component when height is greater than 310px

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js

Added Witness Designation in review page

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js

Fix related to cache issue in Order Pdf

---

backend/summons-svc/src/main/java/digit/config/Configuration.java
backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
backend/summons-svc/src/main/resources/application.properties

add cmpnumber in summon pdf

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
utilities/dristi-pdf/src/orderHandlers/acceptAdrApplication.js
utilities/dristi-pdf/src/orderHandlers/orderForInitiateReschedule.js
utilities/dristi-pdf/src/orderHandlers/rejectAdrApplication.js
utilities/dristi-pdf/src/orderHandlers/rejectReschedulingRequest.js
utilities/dristi-pdf/src/orderHandlers/rescheduleRequestJudge.js

https://github.com/pucardotorg/dristi/issues/2552

added and changed placeholder for multi eSign

---

backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/config/CustomAuthenticationProvider.java
backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/ServiceCredential.java
backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/service/IcopsService.java
backend/icops_integration-kerala/src/main/resources/application.properties

enrich authentication with auth type

---

backend/icops_integration-kerala/src/main/resources/application.properties
backend/summons-svc/src/main/resources/application.properties

change the context path for icops

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js

https://github.com/pucardotorg/dristi/issues/2652
Changes made: corrected key for complainant designation in config

#2652 [BUG]: [PROD SUPPORT]: [SCRUTINY]: [COMPLAINANT DESIGNATION NOT SHOWING] 

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

handled multiple time calling docviewer files

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

issue- https://github.com/pucardotorg/dristi/issues/2662
Changes made: added Complainant, Accused or Witness in front of the names (in Bracket) respectively.

[#2662] PROD SUPPORT: NOT SHOWING WHETHER A PERSON IS COMPLAINANT OR ACCUSED -> fixed

---

frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/downloadPdfWithLink.js
frontend/micro-ui/web/src/setupProxy.js

RequiredDocuments and Scrutiny Checklist url changes.
Removed the asset url from setupProxy and added it to globalConfigs.
https://github.com/pucardotorg/dristi/issues/2663

RequiredDocuments and Scrutiny Checklist url changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

https://github.com/pucardotorg/dristi/issues/2666
added date validation for dateOfDispatch, it can't be before issuanceDate while Filing the case.

added date validation for dateOfDispatch, it can't be before issuanceDate

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js

#2664
previously it was showing as "first name" + " last name" + "middle name" , i changed into  "first name" + "middle name" + " last name"

modified the advocate display name format in nyaya mitra screen

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js

#2665
replaced + to & in epost payment screen

replaced + to & in epost payment screen

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js

issue- https://github.com/pucardotorg/dristi/issues/2659
Summary: Made changes in date format to dd-mm-yyyy like how we are doing elsewhere in the application.

[ #2659]: PROD SUPPORT: Date format should be dd-mm-yy

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js

Issue- https://github.com/pucardotorg/dristi/issues/2659
Changes made: switched month and date -> updated time format is dd-mm-yyyy

updated minor code change in [#2659]

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

issue- https://github.com/pucardotorg/dristi/issues/2659
changes made: - fixed date format to dd-mm-yyyy in notice via epost

Bug 2659 date format canges in notice via epost payment modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js

issue- https://github.com/pucardotorg/dristi/issues/2659
fix:  added date format change in notice via email, sms

[2659 update]: added date format change in notice via email, sms

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OwnerColumn.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/VoidSubmissionBody.js

Feature 2637 copy

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Name of the person submitting the applications should come in owner/parties column of submission
Fetching name of the logged in individual using userInfo and sending name from there as it is in the owner while creating application.

sending owner as name of the individual who is filing the application

---

utilities/dristi-pdf/src/caseBundle/generateIndex.js

remove bad function call from generate index for case bundle

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

Issue- https://github.com/pucardotorg/dristi/issues/2677
Added cheque amount from all the cheques in the case of full liability.
https://jam.dev/c/d0d67cdf-af6a-4a10-b91c-1309602eddea

[#2677]: PROD SUPPORT: 2 cheque amount not adding when we select Full Liability 

---

backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java

added blank space validation in casetitle

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js

registration req of advocate bug fix

---

backend/case/src/main/java/org/pucar/dristi/service/CacheService.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java

decrypting data received from DB

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js

Download Submission Bug Fix Success Modal

Download submission fix in success modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js

multiple delay condonation application were being created on clicking register case button -> fixed

[#2661]: PROD SUPPORT: 2 Delay condonations showing in submissions 

---

utilities/dristi-pdf/src/caseBundle/generateIndex.js

accused name and year fix in case bundle

accused name and year fix in case bundle

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js

update to role of benchclerk to map the expected config
fix for https://github.com/pucardotorg/dristi/issues/2556

update to role of benchclerk to map the expected config

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/HearingOverlayDropdown.js

ISSUE: https://github.com/pucardotorg/dristi/issues/2691
corrected filter on clicking 3 dots drop down.

[ 2691 ]:PROD SUPPORT: HEARING: 3 dots button near Start Hearing button not working

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/HearingOverlayDropdown.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js

ISSUE: https://github.com/pucardotorg/dristi/issues/2691
Disabled options css fix.
https://jam.dev/c/51036cc8-3c65-4073-9864-db7a9d8b56f8

[ 2691 - UPDATE ]: PROD SUPPORT: HEARING: 3 dots

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js

update the clerk and court staff config same as judge

---

backend/order/src/main/resources/db/migration/main/V20241217113500__order__ddl.sql

Feature 2695 increase comment size to 1000

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js

https://github.com/pucardotorg/dristi/issues/2711
https://github.com/pucardotorg/dristi/issues/2712
error page fix, review modal open fix on empty fields

error page fix, review modal open fix on empty fields

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js

Issue- https://github.com/pucardotorg/dristi/issues/2695
increased character limit in text area component to 1000.

[2695]:PROD SUPPORT : While issuing order , the comment section limit, 64 char should be upgraded.

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js

Issue- https://github.com/pucardotorg/dristi/issues/2714
changed Respondent to Accused

[#2714]: BUG || Respondant shown instead of Accused 

---

backend/case/src/main/java/org/pucar/dristi/config/Configuration.java
backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/case/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/case/src/main/resources/application.properties

topics covered in pr : 
CASE_ADMITTED - 1107173140983636255

sms template changes for case p1

---

backend/order/src/main/java/org/pucar/dristi/config/Configuration.java
backend/order/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java
backend/order/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/order/src/main/resources/application.properties

topics covered in pr: 
WARRANT_ISSUED - 1107173208546405882
NEXT_HEARING_SCHEDULED - 1107173140989184457

sms template changes for order service

---

backend/task/src/main/java/org/pucar/dristi/service/TaskService.java

sms-template changes for task service p2

---

backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/evidence/src/main/java/org/pucar/dristi/repository/EvidenceRepository.java
backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java
backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
backend/evidence/src/main/java/org/pucar/dristi/web/models/EvidenceSearchCriteria.java

update in evidence search

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

created basic configs for bail acceptance and reject
#2728

created basic configs for bail acceptance and reject

---

utilities/dristi-pdf/src/caseBundle/generateIndex.js
utilities/dristi-pdf/src/config.js

#2750
Application Heading Change

Application Heading Change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/downloadPdfWithLink.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

Issue- https://github.com/pucardotorg/dristi/issues/2749
Added key for getting image urls from globalConfig.

[ 2749 bug]: Fetch assests for globalconfig from MINIO in SDC Production

---

docs/Case/workflow/case-workflowConfig.json
support/2739-workflow.json5

added CASE_EDITOR role for RESPOND action

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Order for bail config

---

support/2310-mdms-data.json5

update roleactions for business create and update

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

Issue- https://github.com/pucardotorg/dristi/issues/2759
Changes done:
1. max height increased for card content.
2. in cheque details note, repetition removed.
3. numbering for demand details.

[#2759] BUG || Case Details are not shown in UI if number is greater than 7 

---

backend/advocate/src/main/resources/application.properties
backend/application/src/main/resources/application.properties
backend/case/src/main/resources/application.properties

updated YYYY to yyyy for all number format

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js

https://github.com/pucardotorg/dristi/issues/2747

removed RefAppId from admitDismiss case order, pdf fix

---

utilities/dristi-pdf/src/api.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js

https://github.com/pucardotorg/dristi/issues/2747

noticeList in case admit pdf fix

---

common/egov-idgen/src/main/java/org/egov/id/config/Configuration.java
common/egov-idgen/src/main/java/org/egov/id/config/SchedulerConfig.java
common/egov-idgen/src/main/java/org/egov/id/config/SequenceResetService.java
common/egov-idgen/src/main/resources/application.properties

Reset seq num every year

---

common/egov-idgen/src/main/java/org/egov/id/config/Configuration.java
common/egov-idgen/src/main/java/org/egov/id/config/SchedulerConfig.java
common/egov-idgen/src/main/java/org/egov/id/config/SequenceResetService.java
common/egov-idgen/src/main/resources/application.properties

cron job for resetting seq number on jan 1 midnight

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

"generate application" button remains disabled after entering all mand fields in bail flow

---

support/2777-mdms-data.json

https://github.com/pucardotorg/dristi/issues/2777
added two fields in documentType dropdown for SubmitDocuments

added two fields in documentType dropdown for SubmitDocuments

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

https://github.com/pucardotorg/dristi/issues/2781
change cancel to back button in Reason for Void

change cancel to back button in Reason for Void

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
support/2777-mdms-data.json

#2768
#2777
#2781
bug raises in uat

Bug 2768 2777 2781

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/Module.js

Disables refetchOnWindowFocus instead of relying on stale time of the application
#2613

Possible fix for not triggering refresh on focus

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js

added Loader on api call

---

common/egov-idgen/src/main/resources/application.properties

added individual seq to reset every year

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

format epoch date bug #2806

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js

after dca rejected issue fix #2815

after dca rejected issue fix #2815

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

remarks fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

added infobox while generate dca notice order #2803

added infobox while generate dca notice order

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Reset of Remarks for courtstaff

---

backend/task/src/main/resources/db/migration/main/V20250106153200__task__ddl.sql

tenant id index add for task

---

backend/case/src/main/resources/db/migration/main/V20250106152900__case__ddl.sql

tenant id index add for case

---

backend/hearing/src/main/resources/db/migration/main/V20250106151900__hearing__ddl.sql

tenant id index add for hearing

---

support/2818-mdms-data.json

https://github.com/pucardotorg/dristi/issues/2818

added label for error box in e-filing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

fix bug of mulitple dca creating using pending task #2802
fix issue of dca tag not changes after dca application created during register #2807

dca pending task and tag

---

support/2769-mdms-data.json

added info text for date of check
#2769
added  "tooltipValue": "CS_DATE_OF_ISSUANCE_INFO", in  "masterName": "commonUiConfig",
"moduleName": "chequeDetailsConfig",
previous config:
`{
"tenantId": "kl",
"masterName": "commonUiConfig",
"moduleName": "chequeDetailsConfig",
"mdmsPayload": [
{
"id": "bb8eddc2-00d6-43c2-a723-2e456874237d",
"tenantId": "kl",
"schemaCode": "commonUiConfig.chequeDetailsConfig",
"uniqueIdentifier": "1",
"data": {
"id": 1,
"header": "CS_CHEQUE_DETAILS_HEADING",
"subtext": "CS_COMPLAINT_DATA_ENTRY_INFO",
"className": "cheque",
"formconfig": [
{
"body": [
{
"type": "text",
"label": "CS_DISHONOURED_CHEQUE_SIGNATORY_NAME",
"populators": {
"name": "chequeSignatoryName",
"error": "FIRST_LAST_NAME_MANDATORY_MESSAGE",
"validation": {
"pattern": {
"message": …

added info text for date of check

---

utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js

https://github.com/pucardotorg/dristi/issues/2737

adding partyType to DCA Application

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

fixed merge conflict issue in efiling page- DCA- disable form

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

fixed merge conflict issue in efiling delay con page- fixed 

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

issue: https://github.com/pucardotorg/dristi/issues/2825

[BUG]: [sol-dev | Order for accepting the reschedule requests shows the application status as "Rejected".] #2825

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

issue: https://github.com/pucardotorg/dristi/issues/2825

[BUG 2825 in main]: [sol-dev | Order for accepting the reschedule requests shows the application status as "Rejected".] #2825

---

support/2747-mdms-data.json

https://github.com/pucardotorg/dristi/issues/2747

corrected type of notice

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiUploadWrapper.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

fix issue of application without uploading the document in bail, dca and production of document

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiUploadWrapper.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

https://github.com/pucardotorg/dristi/issues/2823

Bug 2823 -  Issue in application without uploading the document

---

backend/analytics/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/application/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/evidence/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/hearing/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/order/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/task/src/main/java/org/pucar/dristi/service/SmsNotificationService.java

updated localization uri in all services for fetching sms template

---

support/2742-mdms-data.json
support/2742-workflow.json

updated workflow action and mdms for tax period for 2742

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submitDocumentConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Master data for document type

---

support/2834-mdms-data.json

added info box for Name of Signatory of Dishonoured Cheque field
#2834
modified mdms data in  "masterName": "commonUiConfig",    "moduleName": "chequeDetailsConfig",
previous mdms data :
` {
"id": "bb8eddc2-00d6-43c2-a723-2e456874237d",
"tenantId": "kl",
"schemaCode": "commonUiConfig.chequeDetailsConfig",
"uniqueIdentifier": "1",
"data": {
"id": 1,
"header": "CS_CHEQUE_DETAILS_HEADING",
"subtext": "CS_COMPLAINT_DATA_ENTRY_INFO",
"className": "cheque",
"formconfig": [
{
"body": [
{
"type": "text",
"label": "CS_DISHONOURED_CHEQUE_SIGNATORY_NAME",
"populators": {
"name": "chequeSignatoryName",
"error": "FIRST_LAST_NAME_MANDATORY_MESSAGE",
"validation": {
"pattern": {
"message": "CORE_COMMON_APPLICANT_NAME_INVALID",
"masterName": "commonUiConfig",
"moduleName": "patternValidation", …

added info box for Name of Signatory of Dishonoured Cheque field

---

support/2835-mdms-data.json

added info box for number of advocates field
#2835
updated mdms data in "masterName": "commonUiConfig",    "moduleName": "advocateDetailsConfig",
previous data : `{
"id": "2da7be57-7170-4dbe-8ad8-b73dd1d11832",
"tenantId": "kl",
"schemaCode": "commonUiConfig.advocateDetailsConfig",
"uniqueIdentifier": "1",
"data": {
"id": 1,
"header": "CS_ADVOCATE_DETAILS_HEADING",
"subtext": "CS_COMPLAINT_DATA_ENTRY_INFO",
"className": "advocate-detail",
"formconfig": [
{
"body": [
{
"key": "isAdvocateRepresenting",
"type": "radio",
"label": "CS_IF_ADVOCATE_IS_COMPLAINANT",
"populators": {
"type": "radioButton",
"error": "CORE_REQUIRED_FIELD_ERROR",
"options": [
{
"code": "YES",
"name": "Yes",
"showForm": true,
"isEnabled": true
},
{
"code": "NO",
"name": "No",
"showForm": false,
"isEnabled": true, …

added info box for number of advocates field

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js

https://github.com/pucardotorg/dristi/issues/2844

changing null to 0 for delayCondonation in payment calculator api

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js

Redirection Fix for Esign, PendingPayment for Bail

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js

Page break fix on redirect from pending task

---

backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
backend/application/src/main/java/org/pucar/dristi/service/WorkflowService.java
backend/application/src/test/java/org/pucar/dristi/service/WorkflowServiceTest.java
backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java

updated code according to workflow changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Naming Correction for documents in order and application view

---

support/2832-mdms-data.json5

#2832
fetch data from mdms for given masters 
update data for these masters using update endpoint

update the workflow state and actions in mdms

---

backend/application/.gitignore
backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
backend/application/src/main/java/org/pucar/dristi/repository/ApplicationRepository.java
backend/application/src/main/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilder.java
backend/application/src/main/java/org/pucar/dristi/repository/rowMapper/DocumentRowMapper.java
backend/application/src/main/java/org/pucar/dristi/web/models/Application.java
backend/application/src/main/java/org/pucar/dristi/web/models/Document.java
backend/application/src/main/resources/db/migration/main/V20250113122200__application__ddl.sql
backend/application/src/test/java/org/pucar/dristi/enrichment/ApplicationEnrichmentTest.java
backend/application/src/test/java/org/pucar/dristi/repository/ApplicationRepositoryTest.java
backend/application/src/test/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilderTest.java
backend/application/src/test/java/org/pucar/dristi/repository/rowMapper/DocumentRowMapperTest.java
backend/application/src/test/java/org/pucar/dristi/validator/ApplicationValidatorTest.java

added documentOrder in application document

---

backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
backend/case/src/main/java/org/pucar/dristi/service/WorkflowService.java
backend/case/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java

setting filingDate when payment is done

---

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java

added validation

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js

https://github.com/pucardotorg/dristi/issues/2842
https://github.com/pucardotorg/dristi/issues/2848
https://github.com/pucardotorg/dristi/issues/2871

filingDate fix in fso, submit button visibility and document order in application review

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

fixed issue of redirection to new tab in hearing page and admit case pending task bug #2853 and #2852

---

support/2752-workflow.json5

case workflow changes to remove ADMISSION_HEARING_SCHEDULED from flow

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

Issue: https://github.com/pucardotorg/dristi/issues/2855
added check if  admission hearing is completed once, "schedule admission hearing" button should not be visible in UI.

[BUG #2855]: Incorrectly showing Schedule Admission hearing 

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomRadioInfoComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

https://github.com/pucardotorg/dristi/issues/2847

reducing opacity for radio button on disable in efiling

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js

display document name in publish Order modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js

Assinges fix for judge send back for correction

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/efilingDocumentKeyAndTypeMapping.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

change name fix for affidavit in Uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentBreakdown.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js

Fix for Get payment total amount from bill instead of payment calculator

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/admissionActionConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Issue: https://github.com/pucardotorg/dristi/issues/2921
Changed "ISSUE NOTICE" button heading, "SCHEDULE ADMISSION HEARING" texts to "ISSUE BNSS NOTICE" and "SCHEUDLE HEARING" respectively.

changed issue notice button heading, schedule admission hearing texts

---

utilities/dristi-pdf/src/api.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js

order search props fix in dristi-pdf

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

fix for 2 RPAD payment for same address is generated

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js

page breaking fix for notice modal

---

docs/DB_Design/Schema_SQL/casediary.sql

added judge_id in diaryentries table

---

backend/dristi-case-pdf/controller/caseController.js
backend/dristi-case-pdf/service/caseService.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
support/2772-mdms-data.json

Added one section of Prayer during Efiling and case pdf chnage

---

utilities/dristi-pdf/src/config.js

https://github.com/pucardotorg/dristi/issues/2922

adding new heading for applications

---

docs/Case/workflow/case-workflowConfig.json

updated case workflow to allow the one who initiated filing to edit the case to return to Draft in progress during e filing and Case reassigned state during scrutiny correction making

Case workflow update to support  edit case when entering signed state

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
support/2891-mdms-data.json

Make for E-Filing: Uploading reply to Legal Demand Notice is not Mandatory

---

backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
backend/scheduler-svc/src/main/java/digit/service/CauseListService.java

Hearing Date Format change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js

Change Hearing Format

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Fix related to Case Type and Case Id in preHearing modal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

https://github.com/pucardotorg/dristi/issues/2949

[hotfix-2949]-added pending task for schedule hearing after case got admitted

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

updated cheque amount to optional field
#2926

updated cheque amount to optional field

---

backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
backend/application/src/main/java/org/pucar/dristi/util/SmsNotificationUtil.java
backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java
backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java
backend/task/src/main/java/org/pucar/dristi/service/TaskService.java

added logs to methods for better debugging

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
support/2948-mdms-data.json

https://github.com/pucardotorg/dristi/issues/2948

showing comments on yes of dca in review

---

backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java
backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/EFillingCalculationCriteria.java
backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/CaseFeeCalculationServiceTest.java

change delay condonation to boolean

---

backend/case/src/main/java/org/pucar/dristi/service/SmsNotificationService.java

fixed case_dismissed issue for sms templates

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
support/2893-mdms-data.json

Enhacement for first letter make capital automatically

---

backend/ab-diary/pom.xml
backend/ab-diary/src/main/java/digit/config/Configuration.java
backend/ab-diary/src/main/java/digit/config/ServiceConstants.java
backend/ab-diary/src/main/java/digit/enrichment/ADiaryEnrichment.java
backend/ab-diary/src/main/java/digit/repository/DiaryRepository.java
backend/ab-diary/src/main/java/digit/repository/querybuilder/DiaryQueryBuilder.java
backend/ab-diary/src/main/java/digit/repository/rowmapper/DiaryWithDocumentRowMapper.java
backend/ab-diary/src/main/java/digit/service/DiaryEntryService.java
backend/ab-diary/src/main/java/digit/service/DiaryService.java
backend/ab-diary/src/main/java/digit/service/WorkflowService.java
backend/ab-diary/src/main/java/digit/util/CaseUtil.java
backend/ab-diary/src/main/java/digit/validators/ADiaryValidator.java
backend/ab-diary/src/main/java/digit/web/controllers/CaseDiaryApiController.java
backend/ab-diary/src/main/java/digit/web/models/CaseCriteria.java
backend/ab-diary/src/main/java/digit/web/models/CaseDiaryDocumentItem.java
backend/ab-diary/src/main/java/digit/web/models/CaseListResponse.java
backend/ab-diary/src/main/java/digit/web/models/CaseSearchRequest.java
backend/ab-diary/src/main/java/digit/web/models/CourtCase.java
backend/ab-diary/src/main/resources/application.properties
backend/ab-diary/src/test/java/digit/service/DiaryEntryServiceTest.java
backend/ab-diary/src/test/java/digit/service/DiaryServiceTest.java
backend/ab-diary/src/test/java/digit/util/UserUtilTest.java
backend/analytics/src/main/resources/application.properties
common/pdf-service/package-lock.json
common/pdf-service/src/EnvironmentVariables.js
common/pdf-service/src/index.js

Diary changes

---

support/2922-mdms-data.json5

updated court name

---

backend/case/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java

updated test case

---

docs/Case/workflow/case-adiary-workflowConfig.json

Allow the judge to update diary entry and regenerate pdf and update diary unsigned pdf

---

common/egov-hrms/src/main/resources/db/migration/main/V20250202154200__alter_hrms_assignment.ddl.sql

delete wrong ddl

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Fix related to making duplicate documents

---

backend/case/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java

encryption issue test case  fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

Pending Task issue fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js

placeholder localisation change

---

common/egov-hrms/src/main/java/org/egov/hrms/web/validator/EmployeeValidator.java

remove validation for toDate as null

---

docs/DB_Design/Schema_SQL/casediary.sql

updated index

---

docs/DB_Design/Schema_SQL/casediary.sql

added unique constraint

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js

Notice placeholder and allow caps letter where required

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js

Fix for filtering on preHearing Modal

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html

NavBar Title Change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomRadioInfoComponent.js
support/3147-mdms-data.json

resetting formdata on individual and entity change

---

backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java

added enrichment of filingDate

---

support/2966-mdms-schema.json5

schema add for mdms

---

support/3178-mdms-data.json5

added mdms data

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

issue: https://github.com/pucardotorg/dristi/issues/3123
For issue and fixes done, take reference from the pr for sol dev: https://github.com/pucardotorg/dristi-solutions/pull/1779

[sol dev bug 3123- cherrypicked in main]: admit case - open modal condition corrected

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js

Issue: https://github.com/pucardotorg/dristi/issues/2968
for Issue and fixes details, take reference to this pr for sol dev: https://github.com/pucardotorg/dristi-solutions/pull/1782

[sol dev bug 2968- updated commit cherry-picked in main]: enable document upload when judge sends remark

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js

Search Text Localisation Text

---

backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java

fixed accessCode changes for old cases

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js

missed places

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentBreakdown.js

added missed code changes while latest sol dev marge
#3191

added missed code changes while latest sol dev marge

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js

updated validation for first name in efiling
#3192

updated validation for first name in efiling

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js

https://github.com/pucardotorg/dristi/issues/3059

enhancement in disabling parties mulitple select dropdown when advocate join

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

added validation when case is reassigned

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
support/3133-mdms-data.json

added warning on leagal demand notice

---

backend/analytics/src/main/java/org/pucar/dristi/service/PendingTaskService.java
backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/analytics/src/test/java/org/pucar/dristi/util/IndexerUtilsTest.java

update pending task for advocate

---

support/3039-mdms-data.json
support/3039-mdms-schems.json5

master data for police station

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js

…
https://github.com/pucardotorg/dristi/issues/3208

[bug-3208] - flag icon show for citizen after edit when case came from scrutiny fix

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/micro-ui-internals/example/src/index.js
frontend/micro-ui/web/micro-ui-internals/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/micro-ui-internals/yarn.lock
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html
frontend/micro-ui/web/src/App.js

CSS version upgrade

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/admissionActionConfig.js

Increase word limit to 1000

---

backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/LitigantRowMapper.java
backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java
backend/case/src/main/java/org/pucar/dristi/web/models/Party.java
backend/case/src/main/resources/application.properties
backend/case/src/main/resources/db/migration/main/V20250218183300__case__ddl.sql
backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilderTest.java
docs/Case/workflow/case-workflowConfig.json
support/3113-workflow.json

multiple response implementation

---

support/2966-mdms-data.json5

master data for employee role mapping

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

https://github.com/pucardotorg/dristi/issues/3073

[Bug-3073]-frontend pending task transfer

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ErrorDataModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

evidence modal css, localization and corresponding litgant fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SearchCaseAndShowDetails.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js

https://github.com/pucardotorg/dristi/issues/3221

Fixed alignment for case search result #3221

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js

https://github.com/pucardotorg/dristi/issues/3215
https://github.com/pucardotorg/dristi/issues/3216
https://github.com/pucardotorg/dristi/issues/3219
https://github.com/pucardotorg/dristi/issues/3257

preselect of dropdown in login page, aDiary header, link and breadcrumb, termCondition changes

---

backend/ab-diary/src/main/java/digit/config/Configuration.java
backend/ab-diary/src/main/java/digit/config/SchedulerConfig.java
backend/ab-diary/src/main/java/digit/config/ServiceConstants.java
backend/ab-diary/src/main/java/digit/service/GenerateDiaryService.java
backend/ab-diary/src/main/resources/application.properties
backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/analytics/src/main/java/org/pucar/dristi/web/models/PendingTask.java
backend/analytics/src/test/java/org/pucar/dristi/config/ServiceConstantsTest.java
backend/analytics/src/test/java/org/pucar/dristi/util/IndexerUtilsTest.java
backend/analytics/src/test/java/org/pucar/dristi/web/models/PendingTaskTest.java
support/2869-mdms-data-2.json

case diary pending task and inbox configuration update

---

backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/analytics/src/test/java/org/pucar/dristi/config/ServiceConstantsTest.java

updated screentype to string in elastic search query

---

support/2883-mdms-data.json5

added role-action mapping for lock-svc

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

show dCA toast to all user

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/public/index.html
frontend/micro-ui/web/webpack.config.js

added for disable cache through index.html

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

update case moved to redirect back on eSign

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ErrorDataModal.js

remove delete for first advocate, css fix in mandatory advocate fields

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WarningModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

added warning modal for new individual

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

isLastPersonSigned condition change

---

backend/analytics/src/main/java/org/pucar/dristi/service/PendingTaskService.java

change the code for updating pending task

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/micro-ui-internals/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html

Resolve conflict

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/micro-ui-internals/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/micro-ui-internals/yarn.lock
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html
frontend/micro-ui/web/src/App.js

Css version upgrade pre deployment

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

calling update on useMemo

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

change update case condition

---

backend/ab-diary/src/main/java/digit/config/Configuration.java
backend/ab-diary/src/main/java/digit/config/ServiceConstants.java
backend/ab-diary/src/main/java/digit/service/GenerateDiaryService.java
backend/ab-diary/src/main/java/digit/service/UserService.java
backend/ab-diary/src/main/resources/application.properties

updated cron expression and generating system user for diary generation

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Bug 3071 uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

calling update on .then

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

esign condition change

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
support/2518-mdms-data.json

added label childern optional

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

sending calculation on redirect

---

support/2869-mdms-data-2.json

updated inbox-configuration mdms

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

adding calculation response in redirect

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js

shifting update call pn redirect back from esign

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js

Adiary redirection fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

adiary pending task fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

https://github.com/pucardotorg/dristi/issues/3281

[bug-3281] - Registered Advocates are getting registration page when they login fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js

add ? in useeffect

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrSeparator.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
support/2518-mdms-data-review-page.json
support/2518-mdms-data.json

Enhacement 2518 witness suggested change uat

---

backend/ab-diary/src/main/java/digit/config/ServiceConstants.java
backend/ab-diary/src/main/java/digit/service/DiaryService.java

add null check for diary entries

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCard.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ScrutinyInfo.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

Make Seperate marking for each date and added warning for them

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/utils/index.js
support/2518-mdms-data-review-page.json

Witness name bug issue fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/CustomEmailTextInput.js

fix localization #3309

---

support/3015-mdms-data.json

cheque date tooltip fix #3015

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customNote.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js

[hotfix-3296] Added info-box under Advocate details #3296

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

Add column for Delivery Date and summons view tab inside case view

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
support/3302-mdms-data.json

added middle name for complaint and witness in review page

---

backend/order/src/test/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichmentTest.java
backend/order/src/test/java/org/pucar/dristi/repository/querybuilder/OrderQueryBuilderTest.java
backend/order/src/test/java/org/pucar/dristi/repository/rowmapper/OrderRowMapperTest.java
backend/order/src/test/java/org/pucar/dristi/service/OrderRegistrationServiceTest.java
backend/order/src/test/java/org/pucar/dristi/validators/OrderRegistrationValidatorTest.java
backend/order/src/test/java/org/pucar/dristi/web/controllers/OrderApiControllerTest.java

Composite Items Test Cases Updates

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

update status Date for sent notice time

---

utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
utilities/dristi-pdf/src/applicationHandlers/cleanName.js

[bug-fix] Advocates: Changes on all Application templates #2922

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js

[bug-fix] #3156

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/topbar.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

Fixed following tickets:
https://github.com/pucardotorg/dristi/issues/2830
https://github.com/pucardotorg/dristi/issues/3222
https://github.com/pucardotorg/dristi/issues/3210
https://github.com/pucardotorg/dristi/issues/3220
https://github.com/pucardotorg/dristi/issues/3113

Hotfix to main

---

backend/ab-diary/src/main/java/digit/repository/querybuilder/DiaryEntryQueryBuilder.java
backend/ab-diary/src/main/java/digit/web/models/CaseDiarySearchCriteria.java

search enabled for referenceId, and referenceType

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js

[bug-fix] #3329 Removed stage column

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ErrorsAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

Fix related to User cannot edit fields not marked by FSO

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js

disable button when join case api called
fix bug of close submit reponse modal https://github.com/pucardotorg/dristi/issues/3341,
add evidence api in join case document upload

fix bug of close submit reponse modal pucardotorg, add evidence api in join case document upload

---

utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js

added time zone for epoch convertor

---

backend/hearing/src/main/resources/application.properties

added limit and offset in api

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

[bug-3331] - Litigant is displaying as empty for the Application for Reschedule Request fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetAllOrderApplicationRelatedDocuments.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
utilities/dristi-pdf/src/utils/orderUtils.js

extractOrderNumber fun type validation

---

frontend/micro-ui/web/micro-ui-internals/example/src/index.js
frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetDiaryEntry.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js

https://github.com/pucardotorg/dristi/issues/3229

[enhance-3229] - BoTD Visible Against Orders From Regular View

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

https://github.com/pucardotorg/dristi/issues/3279

[bug-3279] - remove info box, if all party joined

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js

https://github.com/pucardotorg/dristi/issues/3222

[bug-3222] - the dropdown opens below the screen fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js

[bug-3366] - hide botd from citizen screen

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WarningModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

[hotfix-2901] Removed onSaveDraft modal

---

backend/analytics/src/main/java/org/pucar/dristi/util/CaseOverallStatusUtil.java
backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
backend/evidence/src/main/java/org/pucar/dristi/config/Configuration.java
backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
backend/evidence/src/main/java/org/pucar/dristi/service/SmsNotificationService.java
backend/evidence/src/main/java/org/pucar/dristi/web/models/SmsTemplateData.java

sms template changes

---

backend/case/src/main/java/org/pucar/dristi/service/IndividualService.java

search individual with isDeleted false only

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

https://github.com/pucardotorg/dristi/issues/3370

[bug - 3370] - parties name should include both (comp and acc) fixed

---

backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
backend/evidence/src/main/resources/application.properties

sms templates changes for evidence

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js

[bug-fix] #3261 "Date Added" changed to "Date Issued" in Orders tab

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js

[bug-fix] #3261

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/micro-ui-internals/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html

css-version-upgrade (#2035)

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js

mandatory submission and set term bail combination in published order modal, BOTD fix

---

backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java

enrich hearing for courtcasenumber and cmpnumber

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

enable add location button for judge send back

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js

Transcript history of all hearings in view case - over view tab

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js

[bug-fix] #3355 - Exclude 15th day while calculating Date of Cause of Action fixed

---

support/2869-mdms-data.json

updated url of aDiary

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js

[bug-fix] #3350 Default role removed from registration page

---

backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/analytics/src/test/java/org/pucar/dristi/web/models/PendingTaskTypeTest.java

build failure fix for analytics

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js

redirect on pending task fix from evidenceModal

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js

updated payload  for notification pdf
#3421

updated payload  for notification pdf

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js

added calender css

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

[bug-3420-updated to main]: updated hearing number in order update api

---

backend/epost-tracker/src/main/java/org/pucar/dristi/repository/EPostRepository.java

fix the bug while dev testing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

fix for auto populate fix

---

support/3287-mdms-data.json5

updated mdms data for composite order

---

backend/casemanagement/src/main/java/org/pucar/dristi/service/CaseBundleService.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/controllers/CasemanagerApiController.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/CaseBundleCreateIndexResponse.java
backend/casemanagement/src/main/java/org/pucar/dristi/web/models/ProcessCaseBundlePdfRequest.java
utilities/dristi-pdf/src/caseBundle/generateIndex.js
utilities/dristi-pdf/src/routes/pdfRoutes.js

Feature 2764 main

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

added disable for complaintDetails

---

backend/transformer/src/main/java/org/egov/transformer/models/Hearing.java
backend/transformer/src/main/java/org/egov/transformer/models/OpenHearing.java
backend/transformer/src/main/java/org/egov/transformer/service/HearingService.java
support/2920-mdms-data.json

add substage and other fields

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js

Enhancement 3102 uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js

added hearing sorting based on caseNumber

---

backend/epost-tracker/src/main/java/org/pucar/dristi/config/EPostConfiguration.java
backend/epost-tracker/src/main/java/org/pucar/dristi/repository/EPostQueryBuilder.java
backend/epost-tracker/src/main/java/org/pucar/dristi/repository/EPostRepository.java
backend/epost-tracker/src/main/java/org/pucar/dristi/repository/EPostRowMapper.java
backend/epost-tracker/src/main/java/org/pucar/dristi/service/EPostService.java
backend/epost-tracker/src/main/resources/application.properties
backend/epost-tracker/src/test/java/org/pucar/dristi/repository/EPostQueryBuilderTest.java
backend/epost-tracker/src/test/java/org/pucar/dristi/repository/EPostRowMapperTest.java
backend/epost-tracker/src/test/java/org/pucar/dristi/service/EPostServiceTest.java

done changes to update postal hub names of existing data

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/publishedNotificationModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
support/3114-mdms-data.json

Added order and notification tab

Feature 3114 ordertab main

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
support/3166-mdms-data.json
support/3166-mdms-schema.json

change pending task filter to search on filter text

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js

[enhancement-3386] Localisation Changes for iCops #3386

---

backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java

added logs for start time and end time

---

backend/transformer/src/main/java/org/egov/transformer/consumer/HearingConsumer.java
backend/transformer/src/main/resources/application.properties

add bulk reschedule for hearing update

---

backend/transformer/src/main/java/org/egov/transformer/event/impl/NotificationImpl.java

changed entitytype to notification

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

hearing date BOTD bug fix

---

backend/transformer/src/main/java/org/egov/transformer/consumer/HearingConsumer.java
backend/transformer/src/main/java/org/egov/transformer/models/HearingBulkRequest.java

handle bulk reschedule for update hearing index

---

backend/transformer/src/main/java/org/egov/transformer/consumer/HearingConsumer.java
backend/transformer/src/main/java/org/egov/transformer/models/HearingBulkRequest.java

Bug 2920 transformer

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

[hotfix-3155] COURTSTAFF: Added preview option for notices that are marked as Delivered /undelivered

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

Fix for showing accused data in complaintTab

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

[hotfix-3323] Added submit Document button besides Make an Application button

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js

[bug-fix] #3362-Auto generated business of the day fixed for case dismissed #3414-Close button added 

---

backend/order-management/src/main/java/pucar/repository/ServiceRequestRepository.java
backend/order-management/src/main/java/pucar/util/FileStoreUtil.java
backend/order-management/src/main/java/pucar/util/OrderUtil.java

added generic method for rest template methods

---

backend/order-management/src/main/java/pucar/config/Configuration.java
backend/order-management/src/main/java/pucar/util/OrderUtil.java
backend/order-management/src/main/java/pucar/web/models/IssuedBy.java
backend/order-management/src/main/java/pucar/web/models/Order.java
backend/order-management/src/main/java/pucar/web/models/OrderCriteria.java
backend/order-management/src/main/java/pucar/web/models/OrderListResponse.java
backend/order-management/src/main/java/pucar/web/models/OrderPagination.java
backend/order-management/src/main/java/pucar/web/models/OrderRequest.java
backend/order-management/src/main/java/pucar/web/models/OrderResponse.java
backend/order-management/src/main/java/pucar/web/models/OrderSearchRequest.java
backend/order-management/src/main/java/pucar/web/models/Pagination.java
backend/order-management/src/main/java/pucar/web/models/StatuteSection.java
backend/order-management/src/main/java/pucar/web/models/WorkflowObject.java
backend/order-management/src/main/resources/application.properties

added method in util to update order

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSortComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js

[bug-3447] - e post page redirection fix and ui enhancement

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js

[bug-3342] - Update Summons/Notice/Warrant Pop-Up fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js

[hotfix-3448] Fixed Preview status Issue in UAT CourtStaff

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js

[bug-3435] - action button fixed for bench clerk

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ErrorsAccordion.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js

[bug-fix] #3337-draft saved for arrow functionality fixed  #3414-changed date format to DD-MM-YY

---

backend/order-management/src/main/java/pucar/service/BSSService.java
backend/order-management/src/main/resources/application.properties

fixes during dev testing

---

backend/order-management/src/test/java/pucar/repository/ServiceRequestRepositoryTest.java
backend/order-management/src/test/java/pucar/service/BSSServiceTest.java
backend/order-management/src/test/java/pucar/util/ByteArrayMultipartFileTest.java
backend/order-management/src/test/java/pucar/util/CipherUtilTest.java
backend/order-management/src/test/java/pucar/util/ESignUtilTest.java
backend/order-management/src/test/java/pucar/util/FileStoreUtilTest.java
backend/order-management/src/test/java/pucar/util/FileValidationUtilTest.java
backend/order-management/src/test/java/pucar/util/OrderUtilTest.java
backend/order-management/src/test/java/pucar/util/ResponseInfoFactoryTest.java
backend/order-management/src/test/java/pucar/util/XmlRequestGeneratorTest.java
backend/order-management/src/test/java/pucar/web/controllers/OmsApiControllerTest.java

added test cases

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js

closing modal  on bulk reschedule success
#3440

closing modal  on bulk reschedule success

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js

[bug-fix] #3261 Date Added changed to Date Issued

---

backend/summons-svc/src/main/java/digit/config/Configuration.java
backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
backend/summons-svc/src/main/resources/application.properties

Hotfix 3159 summon pdf changes

---

backend/order-management/src/main/java/pucar/service/BSSService.java
backend/order-management/src/main/java/pucar/util/XmlRequestGenerator.java
backend/order-management/src/main/resources/application.properties
backend/order-management/src/test/java/pucar/util/XmlRequestGeneratorTest.java

3367 bug bulk sign

---

backend/order-management/src/main/java/pucar/service/BSSService.java
backend/order-management/src/main/java/pucar/web/controllers/OmsApiController.java
backend/order-management/src/main/java/pucar/web/models/UpdateSignedOrderResponse.java
backend/order-management/src/main/resources/application.properties
backend/order-management/src/test/java/pucar/web/controllers/OmsApiControllerTest.java

update order end point implementation

---

backend/order-management/src/main/resources/application.properties

updated buffer size limit to 10 mb

---

backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java

added table task filter based on case name and filing Number

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js

added filter to not show deleted and draft orders to citizen
#3463

Bug 3463 main

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomChooseDate.js

[hotfix-3128] Fixed UI for opt-out Date

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js

[hotfix-3151] Added Tooltip for "Learn More" #3151

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/micro-ui-internals/package.json
frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
frontend/micro-ui/web/package.json
frontend/micro-ui/web/public/index.html

CSS version upgrade conflict resolve

---

support/3248-mdms.json

fix for application pending task shown for employee

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js

remove the extra make another submission buttons

---

frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js

[bug-fix] #3464 No one is not able to open dismissed cases Fixed || modal css issue fixed

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js

[bug-fix] #3433 Join hearing button removed from Disposed Cases

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js

added suggested css changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
utilities/dristi-pdf/src/utils/extractOrderNumber.js
utilities/dristi-pdf/src/utils/orderUtils.js

extractOrderNumber export change, advocateName fix in multiple adv case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

remove item in composite order bug fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/orderWorkflow.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Bulk sign redirection from tabs if in pending e-sign stage, added BOTD in additional details of order, download order on addBulk success fix

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderAddToBulkSuccessModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

hide Bulk sign for citizen, enable sign later for bench clerk

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
support/3473-mdms-data.json

[hotfix-3473] FILING: Added infobox to complainaint address #3473

---

common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/consumer/EmailNotificationListener.java

add log for email

---

support/3358-mdms-data.json

added police station in cheque details in mdms

---

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java

update the additionalDetails for reject request

---

frontend/micro-ui/web/micro-ui-internals/example/public/index.html
frontend/micro-ui/web/public/index.html

[bug-fix] #3145 Removed digit logo from title bar, added OnCourts logo 

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js

Reverts pucardotorg/dristi-solutions#2165

Revert "revert those changes related to sorting based on caseID"

---

common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/config/EmailProperties.java
common/egov-notification-mail/src/main/java/org/egov/web/notification/mail/service/ExternalEmailService.java
common/egov-notification-mail/src/main/resources/application.properties

add test email for receiver

---

backend/scheduler-svc/src/main/java/digit/service/CauseListService.java

update the slotting in causelist

---

api_specifications/advocate-api-0.1.0.yaml
backend/advocate/src/main/java/org/pucar/dristi/repository/AdvocateRepository.java
backend/advocate/src/main/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilder.java
backend/advocate/src/main/java/org/pucar/dristi/service/AdvocateService.java
backend/advocate/src/main/java/org/pucar/dristi/web/controllers/AdvocateApiController.java
backend/advocate/src/main/java/org/pucar/dristi/web/models/AdvocateSimpleSearchRequest.java
backend/advocate/src/test/java/org/pucar/dristi/repository/AdvocateRepositoryTest.java
backend/advocate/src/test/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilderTest.java
backend/advocate/src/test/java/org/pucar/dristi/service/AdvocateServiceTest.java
backend/advocate/src/test/java/org/pucar/dristi/web/controllers/AdvocateApiControllerTest.java

Enhancement 3481 uat

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SearchableDropdown.js

[enhancement-3481] Filing: 2 Registered advocate names are not showing to add them in the case

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js

Bug 3485 dev

---

backend/transformer/src/main/java/org/egov/transformer/consumer/HearingConsumer.java
backend/transformer/src/main/java/org/egov/transformer/models/HearingBulkRequest.java
backend/transformer/src/main/resources/application.properties
common/inbox/src/main/java/org/egov/inbox/repository/builder/V2/InboxQueryBuilder.java
common/inbox/src/main/java/org/egov/inbox/util/InboxConstants.java

update the inbox and transformer for hearings

---

backend/treasury-backend/src/main/java/org/egov/eTreasury/config/PaymentConfiguration.java
backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
backend/treasury-backend/src/main/resources/application.properties

add prefix to treasury id

---

backend/case/src/main/java/org/pucar/dristi/web/models/AdvocateDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/AdvocateIdProof.java
backend/case/src/main/java/org/pucar/dristi/web/models/IndividualDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/LitigantDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/ReasonDocument.java
backend/case/src/main/java/org/pucar/dristi/web/models/ReplacementAdvocateDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/ReplacementDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/ReplacementDocumentDetails.java
backend/case/src/main/java/org/pucar/dristi/web/models/TaskJoinCase.java

TaskJoinCase Schema changes

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js

[bugfix-3486] FSO: Give remarks option to the FSO #3486

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

fix related to botd and summons tags

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js

Correct props passing

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

fix related to botd

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
support/3358-mdms-data.json

added police Station in reviewCase

---

backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
backend/task/src/main/java/org/pucar/dristi/config/ServiceConstants.java
backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
backend/task/src/main/java/org/pucar/dristi/util/CaseUtil.java
backend/task/src/main/java/org/pucar/dristi/validators/TaskRegistrationValidator.java
backend/task/src/main/java/org/pucar/dristi/web/models/AdvocateDetails.java
backend/task/src/main/java/org/pucar/dristi/web/models/AdvocateIdProof.java
backend/task/src/main/java/org/pucar/dristi/web/models/AdvocateMapping.java
backend/task/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
backend/task/src/main/java/org/pucar/dristi/web/models/CaseListResponse.java
backend/task/src/main/java/org/pucar/dristi/web/models/CourtCase.java
backend/task/src/main/java/org/pucar/dristi/web/models/IndividualDetails.java
backend/task/src/main/java/org/pucar/dristi/web/models/JoinCaseTaskRequest.java
backend/task/src/main/java/org/pucar/dristi/web/models/LitigantDetails.java
backend/task/src/main/java/org/pucar/dristi/web/models/Party.java
backend/task/src/main/java/org/pucar/dristi/web/models/PendingAdvocateRequest.java
backend/task/src/main/java/org/pucar/dristi/web/models/ReasonDocument.java
backend/task/src/main/java/org/pucar/dristi/web/models/ReplacementAdvocateDetails.java
backend/task/src/main/java/org/pucar/dristi/web/models/ReplacementDetails.java
backend/task/src/main/java/org/pucar/dristi/web/models/ReplacementDocumentDetails.java

validation the pending task

---

backend/task/src/main/java/org/pucar/dristi/util/WorkflowUtil.java

pending task not-created issue fix

---

backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
backend/analytics/src/main/resources/application.properties

changes to not display pending tasks to judge

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

[hotfix-3469] Removed fileStoreId from local storage

---

frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js

Issue: #3557
Problem: Suppose for same edit profile request(here same means same pending task ref id and same date of creation of edit profile request), if a judge creates multiple orders and those orders are in draft stage, once the judge publish any one of these orders, the other orders should not get published.
------>>  now an error message will be displayed if judge wants to publish. 
Note: here same pending task ref id means same editor wants to make request for same litigant, as pending task ref id is a combination of litigant uniqueId and editor uuid and caseid.

[bug 3557]: added error message for duplicate drafted orders for an already approved/rejected edit request
